elastic/elasticsearch-js

CONTRIBUTING.md, src/lib/errors.js
The 504 (Gateway Timeout) response was not being handled by the client. This adds it to the list of HTTP codes to handle.
In addition, it updates the contributing guide to fix a mistake where it listed the unit testing command as `grunt test_unit` instead of `grunt unit_test`.
=> Add 504 error handling and update contributing guide

docs/configuration.asciidoc
It's set to one minute in the [code](https://github.com/elastic/elasticsearch-js/blob/7d14e7d24e5017eb29d6b0998eb6b0e04c2cacb8/src/lib/connection_pool.js#L37).
=> Correct dead timeout in the docs.

docs/api_methods.asciidoc
Although _msearch using the web API will allow the body to not have leading underscores before the keys "index" and "type" (e.g. `{"index": "my-index", "type": "my-type"}
{"query": ... }`), the Javascript Elasticsearch client.msearch will give the error "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed]" if the body follows the same format. Adding the leading underscores fixes this issue.
=> Update elasticsearch-js msearch body format

docs/_examples/count.asciidoc
current example leads to error 400, QueryParsingException, request does not support [filtered]]
=> updated client.count example

src/lib/errors.js
Added support for http error 429: 'Too Many Requests', eg. for bonsai.io
=> Added support for http error 429: 'Too Many Requests'

src/lib/apis/browser_index.js, src/lib/apis/index.js
Enable 2.0 api, which was added in 6.1.0 but not included in the server and browser indexes
=> Add 2.0 api to the indexes

docs/configuration.asciidoc, src/lib/connection_pool.js, src/lib/transport.js, src/lib/transport/find_common_protocol.js, test/unit/specs/transport.js
Fixes #264
If you use https to protect traffic between esjs client and the nodes in your cluster then you can't use sniffing. This is because we use the /_nodes/_all/clear API to populate the connection pool and that API does not know that the nodes speak HTTPS. This change implements the `config.sniffedNodesProtocol` to fix this.
`sniffedNodesProtocol` can be set to a string which will be used as the protocol configuration for each Host object created during sniffing, plain and simple. The default value for this configuration depends on the hosts initially passed to the client, if all of the nodes have the same protocol that protocol is used.
=> implement config.sniffedNodesProtocol

CHANGELOG.md
Simple fix for changelog which listed `8.1`'s release date as September *2014*
=> Fix 2014 typo

package.json
When using the module with browserify it fails to load the lodash dependancy with the latest version of npm, removing the relative path resolves this issue
=> updated the browser dependancy for lodash

src/lib/log.js
Previously the method would conditionally execute one or multiple code paths,
but now the implementation is chosen when the class is initialized and the language
was updated to not specify version numbers.
=> [Log] refactor the Log#listenerCount method

src/lib/transport.js, test/unit/specs/transport.js
We're in the process of converting from postgres to elasticsearch for search.
This module's connection pool is breaking our use of node's domains. Because connections are created with one domain and might service a request for a different domain later when they're reused.
I've modeled my fix after similar fixes in node-pg:
https://github.com/brianc/node-postgres/commit/779c8064f2873b190d6f671b6ecef75852688526
https://github.com/brianc/node-postgres/commit/9c87253aff3609dd3444d53ce5878b1112c7c646
Please let me know what you think.
=> Fixing domain callbacks

docs/_descriptions/search.asciidoc, docs/api_conventions.asciidoc, docs/api_methods.asciidoc, docs/api_methods_0_90.asciidoc, docs/api_methods_1_0.asciidoc, docs/api_methods_1_1.asciidoc, docs/api_methods_1_2.asciidoc, docs/api_methods_1_3.asciidoc, docs/api_methods_1_4.asciidoc, docs/api_methods_1_5.asciidoc, docs/api_methods_1_6.asciidoc, docs/api_methods_1_7.asciidoc, docs/api_methods_2_0.asciidoc
Adding [bodybuilder](https://github.com/danpaz/bodybuilder) as yet another option of query builders. This one supports [combining query clauses using boolean queries](https://www.elastic.co/guide/en/elasticsearch/guide/current/bool-query.html), e.g.
```js
new Bodybuilder().query('match', 'title', 'quick')
.notQuery('match', 'title', 'lazy')
.orQuery('match', 'title', 'brown')
.orQuery('match', 'title', 'dog')
.build()
```
creates
```js
{
"query": {
"bool": {
"must":     [  { "match": { "title": "quick" }} ],
"must_not": [  { "match": { "title": "lazy"  }} ],
"should":   [
{ "match": { "title": "brown" }},
{ "match": { "title": "dog"   }}
]
}
}
}
```
The library is under active development (e.g. need to support the new way of combining filters and queries in the 2.0 dsl) and my hope is to …
=> Add bodybuilder to list of query building libraries.

docs/configuration.asciidoc, scripts/generate/templates/configuration_docs.tmpl, src/lib/connectors/http.js, test/unit/specs/http_connector.js
Fixes #327 
Implements a `createNodeAgent()` function for the config ([see docs](https://github.com/spalger/elasticsearch-js/blob/809f545dee261547a0849cba6c83ca8c5e351918/docs/configuration.asciidoc#user-content-config-create-node-agent))
=> Implement createNodeAgent config

src/lib/log.js
* Param name in docs didn't match code: `output => config`.
* Documented structure of param was incorrect: `config => config.log`.
* Document `level|levels` as aliases.
=> Corrections to log source docs.

docs/transport.asciidoc, src/lib/transport.js
`url` does not seem to be a valid param at this time.
In the asciidoc `query` is only documented as accepting an object. In practice, passing a string seems to be supported. Is that something you wish to document, or should I edit that out of `transport.js`?
=> Fix Transport request doc issues.

src/lib/transport.js
See #226. Another approach would be to construct the request information in `src/lib/transport` and leave `src/lib/connectors/http` untouched, if it's preferable for some reason. I don't have a great understanding of how the connectors / transport interact. Either way, [this](https://github.com/jmm/elasticsearch-js/blob/7bc7d0becbd42255d7d5c0187664f217dbdf28be/src/lib/connectors/http.js#L154-L163) is duplicating code from [`src/lib/log`](https://github.com/elastic/elasticsearch-js/blob/0e3fe1586fd867275fd0e9abb7126724be3d3761/src/lib/log.js#L292-L298) for massaging the request data to be suitable input for `url.format()`. So perhaps that should be extracted and shared.
I'm checking this with something like:
```js
new elasticsearch.Transport({
host: 'whatever.example:9200',
log: 'error', …
```
=> Enhance HTTP connector / transport error messages with more detail

src/lib/host.js
window can be defined and yet window.location can be undefined: both "window" and  "window.location" must be defined to access to "protocol" information.
I encountered this problem where "window" was defined but not "window.location". This append when transpiling js file in a express-react-browserify env.
Regards
=> Update host.js => window.location is not defined

docs/browser_builds.asciidoc
Adding a link to the React example in the docs. Please let me know if this looks okay, and thanks!
=> Add a note pointing to the React browser example

test/utils/jenkins-reporter.js
Now that grunt-esvm logs based on the default elasticsearch logging, and since the tests are designed to stress elasticsearch errors, the output of the tests is a now a mess. 
This is because esvm is logging to stdout in a way that we can't shim, probably because it's capturing a reference to the original `stdout.write()` before we monkey-patch it.
This is an investigation to see if we can do it early enough.
=> [jenkinsReporter] hook into stdio earlier

src/lib/connectors/http.js
As HTTP/HTTPS Agent defaults keepAlive to false, in the case where we desire HTTP keep-alive, it needs to be set appropriately in the http(s).Agent constructor options. This sets it in accordance with the http keepAlive connector option.
=> Add proper support of http.Agent keepAlive

docs/quick_start.asciidoc
there was a missing t for the word against on line 130 of the quick start document
line use to read:
// match the query agains all of
=> fixes typo in quick start doc

src/lib/log.js, test/unit/specs/log.js
There are two major advantages to JSON.stringify over util.inspect:
1.) JSON.stringify defaults to recursively printing deeply nested
objects.
2.) JSON.stringify output is JSON, meaning it can be taken directly from
the output and used wherever JSON is accepted. util.inspect output is
JSON-like, but also includes other annotation such as the types of
various values, as well as functions on objects.
One possible downside is that JSON.stringify cannot print objects with
recursive structure without fore-knowledge of that structure, which is
of course not possible in a logger.
Note: I have a particular use case in mind with this pull request: when
listening to the `debug` log level, the Elasticsearch module prints every
Elasticsearch query, which is excellent. However, due to the nature of …
=> Use JSON.stringify to log objects

src/lib/client.js, src/lib/client_action.js
This PR makes the client instance available to namespaced plugins.
I was planning to add tests, but it doesn't look like there are currently any tests for the namespace stuff.
=> Pass the Client instance to ClientAction namespaceFactory

grunt/config/esvm.js, package.json, scripts/Version.js, scripts/generate/index.js, scripts/generate/js_api.js, scripts/generate/templates/api_file.tmpl, scripts/generate/templates/index.js, src/lib/transport/find_common_protocol.js, src/lib/utils.js, test/fixtures/keepalive.js
I'm doing some memory tests and from the looks of it lodash 4 is the number one cause for memory-thrashing in esjs version 4+. This reverts to version 2.x temporarily until we can find a better solution.
=> Rollback lodash

src/lib/serializers/json.js, test/unit/specs/transport.js
Per https://github.com/elastic/elasticsearch/pull/23049 the `application/x-ldjson` content type for bulk requests is being removed in favor of the `application/x-ndjson` content type. This PR updates the Elasticsearch JS client to comply with the Elasticsearch change.
=> Updating bulk JSON content type

src/lib/loggers/index.js
When using this library in eg. AWS Lambda environment the console logger
is a lot more usefull than stdio.
=> export console logger in non browser environments

docs/_descriptions/search.asciidoc, docs/api_conventions.asciidoc, docs/api_methods.asciidoc, docs/api_methods_2_4.asciidoc, docs/api_methods_5_0.asciidoc, docs/api_methods_5_1.asciidoc, docs/api_methods_5_2.asciidoc
Adding [elastic-builder](/sudo-suhas/elastic-builder) to the list of query builders(5.x, 2.4). The library aims for 100% support for the 5.x query/aggregations DSL.
```js
const bob = require('elastic-builder'); // the builder
const requestBody = bob.requestBodySearch()
.query(
bob.boolQuery()
.must(bob.matchQuery('last_name', 'smith'))
.filter(bob.rangeQuery('age').gt(30))
);
requestBody.toJSON() 
{ 
"query" : { 
"bool" : { 
"must" : { 
"match" : { "last_name" : "smith" } 
}, 
"filter" : { 
"range" : { "age" : { "gt" : 30 } } 
} 
} 
} 
} 
```
The library also has 100% test coverage. The docs, which are hosted [here](https://elastic-builder.js.org/docs/), are next on the roadmap for improvement with examples and better presentation.
I have also removed the link(in 5.x docs) to the now …
=> Add elastic-builder to list of query building libraries.

package.json, src/lib/connectors/http.js
Fixes #640 
Unit tests pass, my limited testing in Kibana didn't bring up any issues, and as far as @mattiasholmlund and I can tell this should work.
=> [npm] upgrade agentkeepalive from 2.2.0 to 3.4.1

package.json, webpack_config/angular.js, webpack_config/browser.js, webpack_config/jquery.js, webpack_config/lib.js
Inspired by @dominykas question in #630 I decided to look into browser version support and realized that there wasn't any transpiling happening to make sure that browser client is compatible with legacy browsers like IE 11. This fixes that by transpiling the bundles with the `@babel/preset-env` targeting `last 2 versions, > 5%, Safari 7, // for PhantomJS support`, which currently translates to:
http://browserl.ist/?q=last+2+versions%2C+%3E+5%25%2C+Safari+7
=> [webpack] use babel to ensure legacy browser compatibility

docs/extensions.asciidoc
Backports the following commits to 15.x:
- [docs/extensions] mention superagent-elasticsearch  (#664)
=> [15.x] [docs/extensions] mention superagent-elasticsearch (#664)

docs/logging.asciidoc
Backports the following commits to 15.x:
- 📖 fix badly-formatted link in logging docs (9c98262)
=> [15.x] 📖 fix badly-formatted link in logging docs

src/lib/serializers/json.js, test/unit/specs/json_serializer.js
I just implemented suggestion by @WesTyler and added some unit tests to ensure it is working as it should. All other tests are passing. Closes #504
=> Fix: Serialization does not handle non-enumerable properties in Node <5.x

src/lib/serializers/json.js, test/unit/specs/json_serializer.js
Backports the following commits to 15.x:
- Fix: Serialization does not handle non-enumerable properties in Node versions < 5.x  (#677)
=> [15.x] Fix: Serialization does not handle non-enumerable properties in Node versions < 5.x (#677)

docs/configuration.asciidoc, scripts/generate/js_api.js, src/lib/apis/0_90.js, src/lib/apis/1_7.js, src/lib/apis/2_4.js, src/lib/apis/5_0.js, src/lib/apis/5_1.js, src/lib/apis/5_2.js, src/lib/apis/5_3.js, src/lib/apis/5_4.js, src/lib/apis/5_5.js, src/lib/apis/5_6.js, src/lib/apis/6_0.js, src/lib/apis/6_1.js, src/lib/apis/6_2.js, src/lib/apis/6_3.js, src/lib/apis/6_x.js, src/lib/apis/master.js, src/lib/transport.js, test/unit/specs/client.js, test/unit/specs/transport.js
Currently ping does not respect defaults set on client instantiation.   The only way to override is by setting request parameters. 
This sets the ordering from:
1) requestTimeout param
2) 3000
to:
1) pingTimeout param
1) requestTimeout param
1) instantiated pingTimeout
1) default pingTimeout
Closes https://github.com/elastic/elasticsearch-js/issues/547
=> [ping()] determine ping timeout at runtime

.travis.yml, package.json
Adds Travis support.
The test are still failing on Node v6 because some regex are not valid on Node ≤ 8, I will fix the test runner in the `refactor-test-suite` branch.
=> Add Travis

.ci/run-tests, .ci/test-matrix.yml
Per our conversation earlier today, in order to migrate to running tests on https://clients-ci.elastic.co/, we'll need to establish some conventional structure for controlling the Jenkins jobs. The first convention is a build script that Jenkins will execute, and the second will be a definition of the matrix axes values to cover the version combinations that we'd like to test.
Having those two items defined within the repository means that only minimal tweaking of the actual Jenkins job itself will be required in the future.
I tried to match the existing matrix from the [refactor-test-suite branch .travis.yml file](https://github.com/elastic/elasticsearch-js/blob/refactor-test-suite/.travis.yml) for the initial setup. Feel free to suggest different naming for things if they're not what …
=> Add initial structure for running tests on clients-ci

docs/configuration.asciidoc
Closes #695 
This PR adds documentation for the `serializer` configuration option. From the commit history, it looks like this file _might_ be generated, so please let me know if there's anywhere else I need to update. I'm not familiar with the asciidoc format, but I tried to follow the doc patterns I saw in the rest of the file so I hope it's correct.
=> Document serializer configuration option

index.js, test/unit/client.test.js
With this new functionality, we allow users to extend the base API of the client with new methods.
```js
// add a single method
client.extend('method', ({ makeRequest }) => {
return (params, options) => {
// validate parameters
return makeRequest(params, options)
}
})
// add a namespace and multiple methods
client.extend('namespace.method', ({ makeRequest }) => {
return (params, options) => {
// validate parameters
return makeRequest(params, options)
}
})
// then access them!
await client.method(...)
await client.namespace.method(...)
```
=> Added extend method

docs/child.asciidoc, index.d.ts, index.js, lib/ConnectionPool.d.ts, lib/ConnectionPool.js, lib/Transport.d.ts, lib/Transport.js, test/unit/child.test.js, test/unit/connection-pool.test.js, test/unit/selectors.test.js, test/unit/transport.test.js
With this pr we introduce the `client.child` API, which returns a new client instance that shares the connection pool with the parent client.
This feature can be handy if you need to have multiple client instances with different configurations, but with a shared connection pool.
Example:
```js
const { Client } = require('@elastic/elasticsearch')
const client = new Client({ node: 'http://localhost:9200' })
const child = client.child({
headers: { 'x-foo': 'bar' },
requestTimeout: 1000
})
client.info(console.log)
child.info(console.log)
```
**Open questions:**
- Currently, the event emitter is shared between the parent and the child(ren), is it ok?
- Currently, if you extend the parent client, the child client will have the same extensions, while if the child client adds an extension, the …
=> Child client support

lib/Connection.d.ts, lib/Connection.js, test/unit/connection.test.js
Handles `console.log` and `utils.inspect` invocations for a better debugging experience.
`agent` and `ssl` are hidden since they made the logs very hard to read.
The user can still access them with `instance.agent` and `instance.ssl`.
=> Inspect Connection

docs/api_param_types.asciidoc, docs/configuration.asciidoc, scripts/generate/templates/configuration_docs.tmpl
This modifies the legacy client documentation so that it is is
compatible with Asciidoctor. With these changes asciidoctor renders the
same way as asciidoc, module spacing and a couple of auto-generated ids.
I'm willing to ignore the auto-generated anchors because these are
legacy docs.
=> Make legacy docs asciidoctor compatible

docs/changelog.asciidoc
The changelog had a link to `/current/configuration.html` which isn't in
the current version of the docs anymore. This changes the link from a
fully qualified link to an in-book link.
=> Docs: Fix link in changelog

docs/index.asciidoc, docs/reference.asciidoc, scripts/utils/generateDocs.js
Fixes some outbound links in the API reference. These are caused by bad
links in Elasticsearch's json spec files. We've filed and issue with
Elasticsearch here:
https://github.com/elastic/elasticsearch/issues/40596
but for now this works around the bad links.
=> Docs: Fix the API reference

scripts/utils/generateDocs.js
Handles a few "special" doc urls from ES's api spec files. These are
only a problem in 6.x but we'd like to keep the generateDocs script the
same across all branches for easier backporting.
=> Docs: Handle more funny cases from ES api spec

scripts/utils/generateDocs.js
The ingest docs in Elasticsearch doing point to the actual ingest APIs.
This makes up generate links to the real APIs instead, fixing some
broken links in the 5.x docs in the process.
=> Docs: Fix ingest doc links

lib/ConnectionPool.d.ts, lib/ConnectionPool.js, lib/Transport.js, test/behavior/sniff.test.js, test/unit/connection-pool.test.js, test/utils/buildCluster.js
=> Support for publish_address as hostname/ip:port

docs/configuration.asciidoc, index.d.ts, lib/Connection.d.ts, lib/Connection.js, test/unit/connection.test.js
With this pr we add the support for a custom http(s) agent passed as a parameter instead of the http agent options.
In any case, you will use the same `agent` configuration option.
```js
const { Agent } = require('http')
const { Client } = require('@elastic/elasticsearch')
const client = new Client({
node: 'http://localhost:9200',
agent: new Agent({ ... })
})
client.info(console.log)
```
Related: https://github.com/elastic/elasticsearch-js/issues/808 https://github.com/elastic/elasticsearch-js/issues/809
=> Custom http agent support

api/api/data_frame.get_data_frame_transform_stats.js, api/requestParams.d.ts, docs/reference.asciidoc, docs/typescript.asciidoc, lib/Transport.d.ts, scripts/utils/generateRequestTypes.js, test/types/index.ts
With this change, it's now easier to use TypeScript with the client.
The ApiResponse now accepts a [generics](https://www.typescriptlang.org/docs/handbook/generics.html) that defaults to `any`, same for every API method that might need a body.
The documentation has been updated accordingly.
I would like to thank @fox1t for the suggestions :)
=> Improve typings

docs/usage.asciidoc
Rename constant `requesty` to `request` which is referred to later in the example.
=> Fix a typo in usage example

.ci/test-matrix.yml, .npmignore, .travis.yml, README.md, docs/breaking-changes.asciidoc, docs/introduction.asciidoc, package.json
Node.js v6 will go EOL at the end of April 2019, and already two of the production dependencies of the client have already dropped support for it, and soon others will do *(as well as development dependencies)*.
Furthermore, since Node.js will go in EOL it will never get security patches, plus, also OpenSSL-1.0.2 will go EOL [this year](https://github.com/nodejs/Release#release-schedule); to avoid risks for the client users it is better to drop support for Node.js v6 right away.
=> Drop Node.js v6 support

index.d.ts, lib/Transport.d.ts
Follow-up on suggestions from https://github.com/elastic/elasticsearch-js/issues/813 and https://github.com/elastic/elasticsearch-js/pull/817.
=> Updated typings

lib/Transport.d.ts
Updated `RequestEvent` to use parameterized type `T`.  In reference to:
https://github.com/elastic/elasticsearch-js/pull/819#issuecomment-484594841
=> Update RequestEvent to use parameterized type T

.ci/test-matrix.yml, .travis.yml, package.json
=> Node v12 and bumped dependencies

lib/ConnectionPool.js, test/behavior/resurrect.test.js
=> Fix resurrect timeout formula

lib/ConnectionPool.js, test/unit/connection-pool.test.js
Simplified internal logic and added test for IPv6.
=> Better handling of hostname/ip:port format

lib/Connection.js, lib/ConnectionPool.js, test/unit/connection-pool.test.js, test/unit/connection.test.js
=> Support for non-friendly chars in url username and password

docs/configuration.asciidoc
=> Docs: added missing configuration options

api/api/count.js, api/api/create.js, api/api/delete.js, api/api/delete_by_query.js, api/api/exists.js, api/api/exists_source.js, api/api/explain.js, api/api/get.js, api/api/get_source.js, api/api/index.js, api/api/ml.find_file_structure.js, api/api/msearch.js, api/api/mtermvectors.js, api/api/reindex.js, api/api/termvectors.js, api/api/update.js, api/api/update_by_query.js, api/requestParams.d.ts, docs/reference.asciidoc
=> API generation

api/api/clear_scroll.js, api/api/scroll.js
elastic/elasticsearch/pull/44238 moved several Elasticsearch APIs to a REST APIs section.
As a result of that move, some pages were converted to anchored sections. This will fix links to those pages once the above PR is re-applied.
=> [DOCS] Fix broken links for ES API docs move

docs/authentication.asciidoc, docs/configuration.asciidoc, docs/reference.asciidoc, index.d.ts, index.js, lib/Connection.d.ts, lib/Connection.js, lib/ConnectionPool.d.ts, lib/ConnectionPool.js, test/types/index.ts, test/unit/client.test.js, test/unit/connection-pool.test.js, test/unit/connection.test.js
- Now you can pass the Basic authentication parameter via a custom option:
```js
{
auth: {
username: 'elastic',
password: 'changeme'
}
}
```
- Added support for [ApiKey](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/security-api-create-api-key.html) authentication:
```js
{
auth: {
apiKey: 'base64ApiKey'
}
}
// or
{
auth: {
apiKey: {
id: 'foo',
api_key: 'bar'
}
}
}
```
- From now you can pass the Elastic cloud username and password inside the standard `auth` option.
```js
{
cloud: {
id: 'name:bG9jYWxob3N0JGFiY2QkZWZnaA==',
},
auth: {
username: 'elastic',
password: 'changeme'
}
}
```
- Instead of storing the authentication parameter, now the `Connection` class caches the precomputed authorization header.
=> Improve authentication handling

index.d.ts
`sniffInterval` configuration option can be boolean as [documented](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/7.x/client-configuration.html) and in [practice](https://github.com/elastic/elasticsearch-js/blob/master/index.js#L83)
=> fix(Typings): sniffInterval can also be boolean

.ci/jobs/elastic+elasticsearch-js+jenkins-pipelines.yml
The pipelines configuration did not like the default values that were being merged from [defaults.yml](https://github.com/elastic/elasticsearch-js/blob/master/.ci/jobs/defaults.yml)
=> Jenkins pipeline testing fixes

docs/configuration.asciidoc
[Documentation](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-configuration.html) for client configuration is incorrect at `sniffEndpoint`. It is currently documented as `requestTimeout`.
=> Fix inaccurate description sniffEndpoint

lib/pool/BaseConnectionPool.js, test/unit/connection-pool.test.js
nodeFilter option was unable to filter nodes where master, data or ingest roles were false because they were defaulting to true when not set.
The example below demonstrates the problem:
```
// roles are returned from the elastic API as a list
roleslist = ['master', 'ingest']
console.log(roleslist)
// The client converts the list to a dictionary
const roles = roleslist.reduce((acc,role) => { acc[role] = true; return acc}, {})
console.log(roles)
// The client then assigns default values to undefined roles
console.log(
Object.assign({'data': true, 'master': true, 'injest': true, 'ml': false}, roles)
)
```
Output:
```
[ 'master', 'ingest' ]
{ master: true, ingest: true }
{ data: true, master: true, injest: true, ml: false, ingest: true }
```
data is `true` when it should be `false`.
=> Fix issue; node roles are defaulting to true when undefined (false) breaking usage of nodeFilter option

api/api/indices.flush_synced.js, api/api/slm.get_stats.js, docs/reference.asciidoc, index.d.ts
Regenerates docs to include the following changes from Elasticsearch documentation:
- Synced flush API link change: https://github.com/elastic/elasticsearch/pull/46634
- SLM API link change: https://github.com/elastic/elasticsearch/pull/46838
Plan to backport to 7.x.
=> [DOCS] Update docs for 'synced flush' and 'SLM' APIs

api/api/indices.flush_synced.js, docs/reference.asciidoc
=> [7.x] [DOCS] Update docs for 'synced flush' and 'SLM' APIs (#972)

docs/usage.asciidoc
This PR fine-tunes the wording of the usage piece in the Node.js book and improves readability.
Related issue: https://github.com/elastic/stack-docs/issues/594
=> [DOCS] Fine-tunes the Node.js client usage section

docs/reference.asciidoc
This PR backports the changes of the following commit to 7.x:
[DOCS] Fine-tunes the Node.js client API reference section #1006
=> [7.x][DOCS] Fine-tunes the Node.js client API reference section

docs/configuration.asciidoc, docs/observability.asciidoc, index.d.ts, index.js, lib/Transport.d.ts, lib/Transport.js, test/unit/client.test.js
This pr adds the support for a easy way to set the `X-Opaque-Id` header.
The `X-Opaque-Id` should be configured in each request, for doing that you can use the `opaqueId` option, as you can see in the following example.
The resulting header will be `{ 'X-Opaque-Id': 'my-search' }`.
```js
const { Client } = require('@elastic/elasticsearch')
const client = new Client({
node: 'http://localhost:9200'
})
client.search({
index: 'my-index',
body: { foo: 'bar' }
}, {
opaqueId: 'my-search'
}, (err, result) => {
if (err) console.log(err)
})
```
Sometimes it may be useful to prefix all the `X-Opaque-Id` headers with a specific string, in case you need to identify a specific client or server. For doing this, the client offers a top-level configuration option: `opaqueIdPrefix`.
In the following …
=> X-Opaque-Id support

docs/page_header.html
Explicitly set page_header.html for 6.8 so that the default notice can be updated for OOM versions.
Prerequisite for: elastic/docs#1528
=> [DOCS] Added older release notice.

docs/authentication.asciidoc
This PR applies the changes of the following commit on the 7.x branch:
[DOCS] Fine-tunes the Node.Js client authentication section #1017
=> [7.x][DOCS] Fine-tunes the Node.Js client authentication section

docs/authentication.asciidoc
This PR fine-tunes the wording of the authentication section in the Node.js book and improves readability.
=> [DOCS] Fine-tunes the Node.Js client authentication section

index.d.ts
This changes the optional username and password under `cloud` to actually be optional.
```diff
cloud?: {
id: string;
// TODO: remove username and password here in 8
-    username: string;
-    password: string;
+    username?: string;
+    password?: string;
}
```
This lets the documented workflow where the `cloud.id` is specified along with traditional `auth` work in TypeScript without cheating.
Prior to this PR, the workaround is:
```ts
return new Client({
cloud: {
id: env.CLOUD_ID,
} as ClientOptions['cloud'], // note: in 7.5.0 it has the optional user/pass as not optional
auth: {
username: env.USERNAME,
password: env.PASSWORD,
},
});
```
=> ClientOptions["cloud"] should have optional auth fields

docs/configuration.asciidoc, docs/examples/reindex.asciidoc, docs/examples/sql.asciidoc, docs/examples/update-by-query.asciidoc, docs/examples/update.asciidoc
=> Added new examples

.ci/run-elasticsearch.sh, .ci/run-repository.sh, .ci/run-tests, .gitignore
Introduces a dedicated `run-repository.sh` for the repository custom
bits.
This allows us to keep `run-elasticsearch.sh` and `run-tests` in sync
through file copying or patches easier.
=> Move to latest .ci script structure

lib/Transport.d.ts
The underlying JavaScript handles arrays of any length. The current type of TransportRequestOptions.ignore, which is [number], only allows arrays with length==1, which looks like a mistake, and prevents the ignore API from being usable when we want to ignore multiple error statuses (which I do).
=> Change TransportRequestOptions.ignore to number[]

docs/child.asciidoc
This PR backports the changes of the following commit to the 7.x branch:
[DOCS] Fine-tunes the Node.Js client child client section #1057
=> [7.x][DOCS] Fine-tunes the Node.Js client child client section

docs/child.asciidoc
This PR fine-tunes the wording of the child client section in the Node.js book and improves readability.
=> [DOCS] Fine-tunes the Node.Js client child client section.

docs/examples/asStream.asciidoc, docs/examples/bulk.asciidoc, docs/examples/get.asciidoc, docs/examples/msearch.asciidoc, docs/examples/scroll.asciidoc, docs/examples/search.asciidoc, docs/examples/suggest.asciidoc, docs/examples/transport.request.asciidoc, docs/examples/typescript.asciidoc, docs/typescript.asciidoc
This PR backports the changes of the following commit to the 7.x branch:
[DOCS] Fine-tunes the Node.Js client Typescript and examples sections #1078
=> [7.x][DOCS] Fine-tunes the Node.Js client Typescript and examples sections.

lib/Transport.js, test/unit/events.test.js, test/unit/transport.test.js
We should skip compression if the body is empty, as some proxy/load balancer could return an error because the body has a wrong format.
Fixes: #1069
=> Skip compression in case of empty string body

api/api/monitoring.bulk.js, docs/reference.asciidoc, scripts/utils/generateDocs.js
This PR updates links that were pointing to a deleted page (https://www.elastic.co/guide/en/elasticsearch/reference/master/es-monitoring.html)
I have updated the links to point to the "Monitor a cluster" top-level section: https://www.elastic.co/guide/en/elasticsearch/reference/master/monitor-elasticsearch-cluster.html
Related to https://github.com/elastic/elasticsearch/pull/52790
=> [DOCS] Fixes out-dated monitoring links

lib/Serializer.js, package.json, test/unit/transport.test.js
This pull request adds a protection mechanism against malicious JSON documents, avoiding prototype pollution attacks.
Further reading: [Square Brackets are the Enemy](https://hueniverse.com/square-brackets-are-the-enemy-ff5b9fd8a3e8)
=> Secure json parsing

docs/authentication.asciidoc, lib/Connection.js, lib/pool/BaseConnectionPool.js, test/unit/client.test.js
Currently, the basic auth takes precedence, which is not correct. This pr addresses this issue.
=> ApiKey should take precedence over basic auth

api/api/transform.cat_transform.js, docs/reference.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/53743
There is a link from https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/master/api-reference.html to the Elasticsearch Reference (in particular a cat transforms API reference page) that is breaking because the file name is changing:
> 11:29:54 INFO:build_docs:Bad cross-document links:
11:29:54 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/master/api-reference.html:
11:29:54 INFO:build_docs:   - en/elasticsearch/reference/master/cat-transform.html
This PR attempts to fix that broken link.
=> [DOCS] Fixes link to cat transforms API

lib/Helpers.js, lib/Transport.js, test/unit/helpers/bulk.test.js, test/unit/helpers/scroll.test.js, test/unit/helpers/search.test.js
As titled, also fixed a minor bug in the stats generation of the bulk helper.
=> Improve code coverage

docs/helpers.asciidoc, lib/Helpers.d.ts, lib/Helpers.js, test/types/helpers.test-d.ts, test/unit/helpers/bulk.test.js
Now you can use an async generator as datasource in the bulk helper!
```js
const { Client } = require('@elastic/elasticsearch')
async function * generator () {
const dataset = [
{ user: 'jon', age: 23 },
{ user: 'arya', age: 18 },
{ user: 'tyrion', age: 39 }
]
for (const doc of dataset) {
yield doc
}
}
const client = new Client({ node: 'http://localhost:9200' })
const result = await client.helpers.bulk({
datasource: generator(),
onDocument (doc) {
return {
index: { _index: 'my-index' }
}
}
})
console.log(result)
```
=> Added async generator support in bulk helper

docs/usage.asciidoc, index.d.ts, lib/Connection.js, lib/Transport.d.ts, lib/Transport.js, lib/errors.d.ts, lib/errors.js, scripts/utils/generateMain.js, test/behavior/sniff.test.js, test/types/client.test-d.ts, test/types/errors.test-d.ts, test/unit/api.test.js, test/unit/connection.test.js, test/unit/errors.test.js, test/unit/transport.test.js, test/utils/MockConnection.js
This pr contains a few feature and fixes:
**Features**
- Added support for aborting a request with the promise style API
- Added `RequestAbortedError` constructor.
**Fixes**
- Until now, aborting a request was blocking the HTTP request, but never calling the callback or resolving the promise to notify the user. This is a bug because it could lead to dangerous memory leaks. From now on if the user calls the `request.abort()` method, the callback style API will be called with a `RequestAbortedError`, the promise will be rejected with `RequestAbortedError` as well.
- The Connection class wasn't consistent regarding errors, as it could return both Node.js errors or client errors (in case of timeouts). With this pr now it only returns client errors, namely `ConnectionError`, `TimeoutError` and …
=> Updated abort behavior

lib/Transport.js, package.json, test/unit/events.test.js, test/unit/transport.test.js
We should not retry if we are sending a stream body, because we should store in memory a copy of the stream to be able to send it again, but since we don't know in advance the size of the stream, we risk to take too much memory.
Furthermore, copying everytime the stream is very an expensive operation.
Solving this issue caused a refactor of the internals of the `transport.request` method, as the compression was handled through streams as well.
=> Do not retry a request if the body is a stream

docs/typescript.asciidoc
=> Updated TypeScript docs

test/behavior/resurrect.test.js, test/behavior/sniff.test.js, test/unit/transport.test.js, test/utils/buildCluster.js
As titled.
The root cause of the issue was that we were testing with timers, and timers are not reliable between different platforms because they can cause timing issues like in this test. I've refactored the code to not depend on timers, but mock the `Date` constructor instead and use the internal state of the client to figure out if a sniff operation is still running or not.
A big thanks to @penge for his initial research.
Closes: #1108 #1142 #1154
=> Fix flaky test

.ci/jobs/defaults.yml, package.json, test/integration/index.js, test/integration/reporter.js, test/integration/test-runner.js
With this pr the integration test will generate a junit report that will make easier to debug test in Jenkins.
=> Generate junit report

.ci/packer_cache.sh, .ci/test-matrix.yml, .github/workflows/nodejs.yml
As titled.
I've also removed Node.js v13, a sit will go EOL soon and it's not an LTS release.
=> Add Node.js v14 to test matrix

README.md, docs/changelog.asciidoc, docs/index.asciidoc
This pro introduces the changelog in the documentation.
It will contain all minors and patches releases, from 7.7.0 it will also contain a brief explanation of the changes.
=> Introduce changelog

.github/workflows/nodejs.yml, docs/helpers.asciidoc, index.js, package.json
=> Disable client Helpers in Node.js < 10.

lib/Transport.js, test/unit/client.test.js, test/unit/helpers/bulk.test.js, test/unit/transport.test.js
As titled.
This change will cause some issues to the [client mock library](https://github.com/elastic/elasticsearch-js-mock/blob/2fe621a9c67a017af8f007c1ee793b3cf34ae616/index.js#L157-L158), which will be handled before releasing this fix.
Closes: https://github.com/elastic/elasticsearch-js/issues/1163
=> Force lowercase in all headers

docs/reference.asciidoc
This PR fixes a link in the API reference docs which is incorrect and now breaks the docs build.
=> [DOCS] Fixes Indices component template link in reference docs

docs/helpers.asciidoc, lib/Helpers.d.ts, lib/Helpers.js, package.json, test/types/helpers.test-d.ts, test/unit/helpers/bulk.test.js, test/unit/helpers/msearch.test.js
If there is a slow producer, the bulk helper might send data with very large period of time, and if the process crashes for any reason, the data would be lost.
This pr introduces a `flushInterval` option in the bulk helper to avoid this issue. By default, the bulk helper will flush the data automatically every 30 seconds, unless the threshold has been reached before.
The same problem might happen with the multi search helper, where the user is not sending search requests fast enough. A `flushInterval` options has been added as well, with a default value of 1 second.
=> Added timeout support in bulk and msearch helpers

docs/helpers.asciidoc, lib/Helpers.js, test/integration/helpers/msearch.test.js, test/unit/helpers/msearch.test.js
With this change, we should completely avoid the edge case (which is **very** hard to reach) where the flush timeout was conflicting with the normal iterator flow.
This pr also renames the returned variable from the `msearch` helper in the test and documentation, to make the API more clear:
```js
// before
s.search(...)
// after
m.search(...)
```
=> Improve helper concurrency

package.json, test/behavior/observability.test.js, test/behavior/resurrect.test.js, test/behavior/sniff.test.js, test/unit/transport.test.js
Migrated tests to use [@sinonjs/fake-timers](https://www.npmjs.com/package/@sinonjs/fake-timers) instead of [lolex](https://www.npmjs.com/package/lolex)
Fixes #1210
=> migrated to FakeTimers

test/benchmarks/actions/001_ping.js, test/benchmarks/actions/002_info.js, test/benchmarks/actions/003_get.js, test/benchmarks/actions/004_index.js, test/benchmarks/actions/005_bulk.js, test/benchmarks/actions/006_bulk-helper.js, test/benchmarks/lib.js, test/benchmarks/run.js
We can now pick which style to use with the `run` option, it can either be `sequential` or `concurrent`.
=> Added option to run the benchmarks sequentially or concurrently

index.mjs, package.json, test/unit/esm/index.mjs, test/unit/esm/index.test.js
With Node.js v12.17.0 ES modules are out without the flag (even if they are still experimental)., this pr adds the support for es modules via [gen-esm-wrapper](https://github.com/addaleax/gen-esm-wrapper).
Closes: https://github.com/elastic/elasticsearch-js/issues/1205
=> ESM support

index.d.ts, index.js, test/unit/events.test.js
This pr introduce two changes which should not impact the surface API:
- Refactored the `client.child` API to allocate fewer objects, this change improves memory consumption over time and improves the child creation performances by ~12%.
- The client no longer inherits from the `EventEmitter` class, but instead has an internal event emitter and exposes only the API useful for the users, namely `emit`, `on`, `once`, and `off`. The type definitions have been updated accordingly.
=> Improve child API

lib/Connection.js
Added the `scheduling: 'lifo'` option to the default HTTP agent configuration to avoid maximizing the open sockets against Elasticsearch and lowering the risk of encountering socket timeouts.
This feature is only available from Node v14.5+, but it should be backported to v10 and v12.
Related: https://github.com/nodejs/node/pull/33278
=> Updated default http agent configuration

lib/Transport.d.ts, scripts/utils/generateRequestTypes.js, test/types/transport.test-d.ts
- The `ignore` paramater is part of the request options and not the request params.
- In the rest-api-spec boolean are written as string (`'true'` and `false'`), this pr generates them as `boolean`.
The type definition fix will be generated once in `master`, `7.x`, and `7.9`.
Related: https://github.com/elastic/kibana/pull/72388 https://github.com/elastic/kibana/pull/72289
=> Fix errors in type definitions

scripts/utils/generateMain.js
As titled.
Fixes #1274 
Example:
```diff
- exists<TResponse = Record<string, any>, TContext = Context>(params?: RequestParams.IndicesExists, options?: TransportRequestOptions): TransportRequestPromise<ApiResponse<TResponse, TContext>>
+ exists<TResponse = boolean, TContext = Context>(params?: RequestParams.IndicesExists, options?: TransportRequestOptions): TransportRequestPromise<ApiResponse<TResponse, TContext>>
```
=> Generate response type as boolean if the request is HEAD only

lib/Connection.d.ts
=> Fix RequestOptions.body type to include null

lib/Transport.js, test/unit/transport.test.js
- If `maxRetries` request option is zero, the client should not use the default
- Check if the `bulkBody` is a stream as well.
=> Fix maxRetries request option handling

test/integration/index.js
By default, the yaml parser will parse look-like dates to date objects, which will break the comparison with the Elasticsearch responses, where dates are represented as string.
=> Integration test: Parse dates as string

test/integration/test-runner.js
This PR improves the cleanup step of the YAML integration tests using wildcard `*` operator for deleting all the templates and all the snapshosts. Here some references:
- [delete template API using wildcards for <index-template>](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-template.html#delete-template-api-path-params)
- [delete spanshost API using * in name](https://www.elastic.co/guide/en/elasticsearch/reference/current/delete-snapshots.html)
I didn't test it but I expect a saving of the overall YAML tests execution time.
=> Improved cleanup yaml tests

docs/reference.asciidoc
This PR fixes a link in the API reference documentation on the 7.x branch.
`{ref}/point-in-time.html`--> `{ref}/point-in-time-api.html`
=> [7.x][DOCS] Fixes link in API reference

docs/configuration.asciidoc
Name field had `string | symbol` but the | was treated as a table column separator.
=> Fix rendering of name field in configuration.md

docs/typescript.asciidoc
* Fixed a typo in the Docs Page for TypeScript support in Node.js client
* Updated complete example in the same page to fix error: Cannot redeclare block-scoped variable 'response'.ts
* Follow Up to changes requested : https://github.com/elastic/elasticsearch-js/pull/1327
=> Fix request typo and redeclare block-scoped variable 'response'

README.md, docs/installation.asciidoc
Since the client **must** follow the stack versioning, it's really hard to follow the [node.js release cadence](https://nodejs.org/en/about/releases/), so we have decided to allow dropping EOL node.js version in minor releases. This pr contains the formalization of the process we will follow in the future.
=> Added node.js support doc

.github/workflows/nodejs.yml, lib/Connection.js, lib/Transport.js, package.json, test/unit/client.test.js, test/unit/connection.test.js, test/unit/transport.test.js, test/utils/MockConnection.js
Until now the client was not verifying the `content-length` header, this pr address this issue.
For supporting this, the unzip process has been moved from the `Connection` class to the `Transport` class.
A byproduct of this pr is the fix of #1088.
Closes: #1088 
/cc: @msisti @tomsquest
=> Handle connectivity issues while reading the body

test/integration/helper.js, test/integration/test-runner.js
=> Updated integration test cleanup code

docs/changelog.asciidoc
=> Fix changelog display

docs/configuration.asciidoc, index.d.ts, index.js, lib/Helpers.js, lib/Transport.js, test/unit/client.test.js, test/unit/helpers/bulk.test.js, test/unit/helpers/scroll.test.js
This pr add a new option named `enableMetaHeader `. If true, adds a header named `'x-elastic-client-meta'`, containing some minimal telemetry data, such as the client and platform version.
=> Added x-elastic-client-meta header

index.js, test/unit/client.test.js, test/unit/helpers/bulk.test.js, test/unit/helpers/scroll.test.js
As titled.
Related: https://github.com/elastic/elasticsearch-js/pull/1373
=> Prereleases in meta header should be displayed as p

docs/changelog.asciidoc
=> Changelog for 7.11

docs/basic-config.asciidoc, index.d.ts, index.js, lib/Helpers.js, lib/Serializer.d.ts, lib/Serializer.js, test/bundlers/parcel-test/package.json, test/types/client-options.test-d.ts, test/unit/client.test.js, test/unit/serializer.test.js
=> Disable prototype poisoning option

.ci/run-elasticsearch.sh, scripts/es-docker-platinum.sh, scripts/es-docker.sh, test/integration/test-runner.js
=> Updated integration test cleanup

scripts/utils/generateApis.js, scripts/utils/generateMain.js, scripts/utils/generateRequestTypes.js
- Automatic recognition of ndjson apis
- If all paths are deprecated, pick one.
=> Updated code generation

test/integration/test-runner.js
=> Wrap inside array ndjson bodies in integration test

api/new.d.ts, docs/typescript.asciidoc, test/types/new-types.test-d.ts
The new types export should be in sync with the legacy ones.
=> Updated new types export

lib/Transport.js, test/unit/transport.test.js
In case of an HTTP error and a `HEAD` request, the body should not be cast to boolean (unless the error is a 404).
Related: https://github.com/elastic/kibana/issues/98890
=> Catch HEAD errors

docs/reference.asciidoc
Removes a link from the generated API docs that makes the docs build to fail.
=> [DOCS] Removes link from API reference that breaks the docs build

lib/Helpers.d.ts, lib/Helpers.js, test/unit/helpers/bulk.test.js
This exposes a `stats()` function on the operation helper that gets returned by `bulk()`. As well, it tracks the number of `noop` results. Let me know if you have any feedback on this pr, thanks!
=> Bulk update improvements

docs/basic-config.asciidoc, docs/connecting.asciidoc, index.d.ts, lib/Connection.js, lib/pool/index.d.ts, test/unit/client.test.js
As titled.
Supersedes https://github.com/elastic/elasticsearch-js/pull/1481.
Closes: https://github.com/elastic/elasticsearch-js/issues/1477.
=> Add support for bearer auth

docs/reference.asciidoc
Looks like some URLs were broken in the API spec that have been fixed in `elastic/elasticsearch` here: https://github.com/elastic/elasticsearch/pull/75388/files
Doing the same here to fix the docs build.
=> Fix URLs for trained model deployments

docs/connecting.asciidoc, index.js, lib/Transport.d.ts, lib/Transport.js, lib/errors.d.ts, lib/errors.js, test/acceptance/events-order.test.js, test/acceptance/observability.test.js, test/acceptance/product-check.test.js, test/acceptance/proxy.test.js, test/acceptance/resurrect.test.js, test/acceptance/sniff.test.js, test/unit/api-async.js, test/unit/api.test.js, test/unit/child.test.js, test/unit/client.test.js, test/unit/events.test.js, test/unit/helpers/bulk.test.js, test/unit/helpers/msearch.test.js, test/unit/helpers/scroll.test.js, test/unit/helpers/search.test.js, test/unit/transport.test.js, test/utils/MockConnection.js, test/utils/index.js
Follows this logic for verifying a connection to Elasticsearch:
Before the first API request:
1. Make an API request to `/`, inspect the response:
2. If call to `/` fails with `401` or `403` pass the check and show a warning (message will be linked later). This happens if the  `monitor` permission missing for user. The subsequent checks must be ignored.
2. If there's no `version` field or if the `version` field value is <6.0.0 raise an error.
3. If there is a `version` field and it's >= 6.0.0 and <7.0.0:
- If there is no `tagline` field or if the `tagline` field value isn't `You know, for Search` raise an error.
4. If there is a `version` field and it's >=7.0.0 and <7.14.0:
- If there is no `tagline` field or if the `tagline` field value isn't `You know, for Search` raise an error.
- If …
=> Verify connection to Elasticsearch

docs/basic-config.asciidoc, docs/connecting.asciidoc, index.d.ts, index.js, lib/Connection.d.ts, lib/Connection.js, lib/pool/BaseConnectionPool.js, lib/pool/index.d.ts, test/acceptance/sniff.test.js, test/unit/client.test.js, test/unit/connection.test.js, test/utils/buildServer.js
As titled.
Usage: 
```js
const client = new Client({
node: 'https://localhost:9200',
caFingerprint: 'string'
})
```
TODO:
=> Support CA fingerprint validation

lib/errors.js, test/acceptance/product-check.test.js, test/unit/client.test.js, test/unit/errors.test.js
=> Show the body as string if the response error can't be read as ES error

lib/Transport.js, test/acceptance/product-check.test.js
As titled.
Closes: https://github.com/elastic/elasticsearch-js/issues/1516
=> Always display request params and options in request event

lib/Transport.js, test/acceptance/product-check.test.js
If the client is busy running an async operation, the `.abort()` call might be executed before sending the actual request. In such case, the error was swallowed, now it will always be emitted, either in the `request` or `response` event.
Closes: #1517
=> Always emit request aborted event

lib/Transport.js
In some edge cases, this might can lead to a conflict and cause unwanted side effects with the product check.
=> Do not use a singleton for EE

.github/workflows/nodejs.yml, test/mock/index.js, test/mock/package.json
As titled, this should help to catch errors before release.
Wait for https://github.com/elastic/elasticsearch-js-mock/pull/20.
=> Add test for mocking library

docs/introduction.asciidoc
As the title states.
[Quick Start](https://elasticsearch-js_1546.docs-preview.app.elstc.co/guide/en/elasticsearch/client/javascript-api/master/introduction.html#_quick_start)
=> [DOCS] Adds a link to the Quick Start section that points to an EC ingest example

docs/basic-config.asciidoc, docs/connecting.asciidoc, index.d.ts, index.js, lib/Transport.d.ts, lib/Transport.js, test/unit/client.test.js
=> Add support for maxResponseSize and maxCompressedResponseSize

README.md, docs/installation.asciidoc
=> Update compatibility info

src/api/api/bulk.ts, src/api/api/create.ts, src/api/api/delete.ts, src/api/api/exists_source.ts, src/api/api/indices.ts, src/api/api/ml.ts, src/api/api/msearch.ts, src/api/api/msearch_template.ts, src/api/api/rollup.ts, src/api/api/scroll.ts, src/api/api/search.ts, src/api/api/transform.ts, src/api/api/update.ts, src/api/kibana.ts, src/api/types.ts, src/api/typesWithBodyKey.ts, src/helpers.ts, test/unit/api.test.ts
As titled, this allows to write code like this:
```ts
import { Client } from '@elastic/elasticsearch'
import * as T from '@elastic/elasticsearch/lib/api/types'
const client = new Client({
node: 'http://localhost:9200'
})
interface Document {
world: number
}
interface Aggregation {
hello: T.AggregationsValueAggregate
}
async function run () {
const result = await client.search<Document, Aggregation>({
index: 'foo',
query: { match_all: {} },
aggregations: {
hello: {
avg: {
field: 'world'
}
}
}
})
result.aggregations.hello // autocompletes to AggregationsValueAggregate
}
```
=> Aggregations should be a generic in responses

package.json
As titled.
Adds two fixes:
- Cleanup abort listener [elastic-transport-js#42](https://github.com/elastic/elastic-transport-js/pull/42)
- perf: minor undici tuning [elastic-transport-js#41](https://github.com/elastic/elastic-transport-js/pull/41)
=> Bump transport version

docs/advanced-config.asciidoc
Fixed the inline code snippets looking funky on the following page:
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/advanced-config.html#_migrate_to_v8
Caused by double backticks being used instead of single backticks.
=> [DOCS] Fix double backticks for inline code snippets

docs/helpers.asciidoc
=> docs: typo

docs/reference.asciidoc
Re-adds discrete tags so the API reference documentation displays on one page.
This PR **does not** update the scripts used to generate this content. @delvedor we'll need to handle that as part of a separate PR.
We'll need to backport this to the 8.1 and 8.0 branches.
https://elasticsearch-js_1654.docs-preview.app.elstc.co/guide/en/elasticsearch/client/javascript-api/master/api-reference.html#_index
=> [DOCS] Add discrete tags to API ref

.ci/packer_cache.sh, .ci/run-repository.sh, .ci/test-matrix.yml, .github/workflows/nodejs.yml, README.md, docs/installation.asciidoc, package.json
As titled, according to our [Node.js support matrix](https://github.com/elastic/elasticsearch-js#nodejs-support).
=> Drop Node.js v12

.github/ISSUE_TEMPLATE/regression.md, docs/typescript.asciidoc, index.d.ts
As titled.
Related: https://github.com/elastic/elasticsearch-js/issues/1665 https://github.com/elastic/elasticsearch-js/issues/1673
=> Update TypeScript docs and export estypes

docs/reference.asciidoc, src/api/api/async_search.ts, src/api/api/bulk.ts, src/api/api/fleet.ts, src/api/api/ml.ts, src/api/api/monitoring.ts, src/api/api/msearch.ts, src/api/api/msearch_template.ts, src/api/api/text_structure.ts, src/api/types.ts, src/api/typesWithBodyKey.ts
The last code generation run contained a bug and ndjson APIs were crafted incorrectly.
This pr fixes this bug.
Fixes: #1686
=> Fix ndjson APIs

README.md, package.json, test/integration/index.js, test/integration/test-runner.js
=> Fix integration test

src/api/api/async_search.ts, src/api/api/search.ts, src/api/types.ts, src/api/typesWithBodyKey.ts
When the same property can both go in the body and in the query, the code will put that property in the body, but the types where not correctly representing that. This pr address this issue.
Fixes: https://github.com/elastic/elasticsearch-js/issues/1589 https://github.com/elastic/elasticsearch-js/issues/1615
=> Types: move query keys to body

docs/reference.asciidoc
This is intended to fix a number of broken links to pages related to the new User Profile API, which are currently behind a feature flag. I think changing the target from `current` to `master` should do the trick. I'm not sure about the labeling but from the errors below we need to fix `8.2`, `8.2`, `current` and `master`.
```
INFO:build_docs:Bad cross-document links:
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/8.2/api-reference.html contains broken links to:
INFO:build_docs:   - en/elasticsearch/reference/current/security-api-activate-user-profile.html
INFO:build_docs:   - en/elasticsearch/reference/current/security-api-get-user-profile.html
INFO:build_docs:   - en/elasticsearch/reference/current/security-api-update-user-profile-data.html …
```
=> [DOCS] Change master to current in user profile API links

docs/reference.asciidoc, src/api/api/async_search.ts, src/api/api/fleet.ts, src/api/api/indices.ts, src/api/api/rollup.ts, src/api/api/search.ts, src/api/api/security.ts, src/api/types.ts, src/api/typesWithBodyKey.ts
Updates the API generator to use `current` instead of `master`.
=> Fix docs URLs to use 'current' instead of 'master'

docs/observability.asciidoc, docs/reference.asciidoc
=> Fix docs URLs to use '8.4' instead of 'master'

docs/observability.asciidoc, docs/reference.asciidoc
=> Fix docs URLs to use '8.0' instead of 'master'

docs/observability.asciidoc
=> Fix docs URLs to use '7.17' instead of 'master'

docs/observability.asciidoc
=> Fix docs URLs to use '7.16' instead of 'master'

docs/observability.asciidoc, docs/reference.asciidoc
=> Fix docs URLs to use '8.2' instead of 'master'

docs/observability.asciidoc, docs/reference.asciidoc
=> Fix docs URLs to use '8.1' instead of 'master'

docs/observability.asciidoc, docs/reference.asciidoc, src/api/api/async_search.ts, src/api/api/fleet.ts, src/api/api/indices.ts, src/api/api/rollup.ts, src/api/api/search.ts, src/api/api/security.ts, src/api/types.ts, src/api/typesWithBodyKey.ts
Backport of https://github.com/elastic/elasticsearch-js/pull/1764
=> Fix docs URLs to use '8.5' instead of 'master'

docs/observability.asciidoc
=> Fix docs URLs to use '6.8' instead of 'master'

package.json
Bumps elastic-transport-js to include the fix for https://github.com/elastic/elastic-transport-js/issues/56
=> Bump @elastic/transport to 8.3.1

docs/index.asciidoc
Related to https://github.com/elastic/clients-team/issues/532.
This PR includes `source_branch` in the docs index file and removes `:branch: master` from the same file. The `jsclient` attribute will point to the respective branch instead of `master` this way.
The changes of this PR need to be backported to:
* 8.7, 8.6, 8.5, 8.4, 8.3, 8.2, 8.1, 8.0, 
* 7.17, 7.16,
* 6.x.
=> [DOCS] Includes source_branch in docs index

docs/index.asciidoc
This PR backports the changes of the following commits to the `8.4` branch:
=> [8.4][DOCS] Includes source_branch in docs index

docs/index.asciidoc
This PR backports the changes of the following commits to the `8.5` branch:
=> [8.5][DOCS] Includes source_branch in docs index

docs/index.asciidoc
This PR backports the changes of the following commits to the `8.6` branch:
=> [8.6][DOCS] Includes source_branch in docs index

.ci/run-elasticsearch.sh, Makefile, scripts/utils/generateApis.js, test/integration/README.md, test/integration/index.js
- Use more inclusive language
- Don't bail on failing tests without `--bail`
- Skip some new tests that do not pass yet, for various reasons
- Default to https when running platinum tests
- Add make targets for local integration testing
- Linter cleanup
- Improvements to integration testing docs
Fixes https://github.com/elastic/elasticsearch-js/issues/1838
=> Fixes to YAML REST integration test suite runner

Makefile, test/integration/README.md, test/integration/index.js
Updates integration test runner and related docs to clean up issues, drop unnecessarily skipped tests, and enable testing of an individual suite or test using `--suite` and `--test` args (which will remain undocumented for the time being, in case they need more polish).
=> Integration test cleanup (#1841

scripts/release-canary.js
Some usability cleanup to the canary release script.
=> Canary release script cleanup

test/integration/test-runner.js
Updates to the integration test runner to ignore a couple errors during cleanup step.
=> Fix integration test runner for 8.8

src/client.ts, test/unit/client.test.ts
Sets an `elasticsearch-js/8.9.0 ...` user-agent header by default instead of using the default `elastic-transport-js/8.3.1 ...` format set by the transport.
Fixes https://github.com/elastic/elasticsearch-js/issues/1737
=> Use correct user-agent header by default

catalog-info.yaml
Cron should run every 12 hours, not every 12 minutes.
=> Fix cron schedule again

.ci/jobs/defaults.yml
JJBB, which generates jobs in clients-ci, needs a default.yml file even if there are no job definitions. Otherwise it cannot delete old job definitions.
=> Fix stuck clients-ci job removal

index.d.ts
Fix `estypesWithBody` definition.
`estypesWithBody` should actually export the legacy types with the body key, located in `src/api/typesWithBodyKey.ts`.
=> Fix estypesWithBody definition

.github/workflows/backport.yml
Upgrades backport github action to v2, which uses a newer version of Node.js
=> Upgrade backport workflow to v2

docs/examples/scroll.asciidoc
Backport of e73eef08 from #1763
=> [Backport 8.7] Update scroll.asciidoc (#1763)

src/helpers.ts
Closes https://github.com/elastic/elasticsearch-js/issues/1751
Fixes the aforementioned issue where a bulk helper call can return wrong information about the erroring operation/document via `onDrop()`, or cause a deserialization error when the request contains a delete action combined with any other action.
The fix is to keep track of `indexSlice` separately in the response handling loop of the `tryBulk` method, instead of deriving it based on the loop counter. The previous approach didn't account for different types of operations which were handled in previous iterations of the loop.
=> fix: keep track of indexSlice explicitly in bulk helper response handling loop

.github/workflows/nodejs.yml
Fixes tests that break on Node.js 14.x by force-installing a version of `npm`. See https://github.com/actions/setup-node/issues/411 for details.
Related: we'll soon stop actively supporting Node.js 14.x. https://github.com/elastic/elasticsearch-js/issues/1855
=> Fix broken Github action on Node 14.x

src/helpers.ts
Backport of de17dc05 from #1759
=> [Backport 8.8] fix: keep track of indexSlice explicitly in bulk helper response handling loop (#1759)

docs/typescript.asciidoc
Elasticsearch has a lot of repositories on github. It is not obvious where the elasticsearch typescript definitions are defined. This PR updates the elasticsearch-js typescript documentation with a link to  elasticsearch-specification github repository to point users to the correct location for making typescript contributions.
=> add link to elasticsearch-specification github repository in typescript documentation

package.json
Upgrades the transport to fix a memory leak caused by an outdated version of Undici.
See https://github.com/elastic/elastic-transport-js/issues/63, fixed by https://github.com/elastic/elastic-transport-js/pull/66.
=> Upgrade transport to 8.3.2

docs/typescript.asciidoc
Backport of 0ab63df5 from #1907
=> [Backport 8.8] add link to elasticsearch-specification github repository in typescript documentation (#1907)

.buildkite/pipeline.yml, catalog-info.yaml
No longer run integration tests on PRs and older branches. Also stops running those tests on Node 14.x.
The team has discussed the value of these, so I'm quieting them down a bit while we decide.
=> Stop running integration tests on PRs

test/unit/helpers/bulk.test.ts
Thanks again to @karlriis for the fix in https://github.com/elastic/elasticsearch-js/pull/1759. Just adding a test to verify that this does indeed solve the problem. Running the test on commit 5d37ca6489dd9ed70f4ac4ff14bad49f69a5a74a failed in a way described in https://github.com/elastic/elasticsearch-js/issues/1751, and passes on all commits after de17dc050c38bb8dd47c0c0b341e1a273e63559e.
=> Add test to verify bulk helper index drift fix

api/requestParams.d.ts, package.json, scripts/utils/generateRequestTypes.js, test/unit/client.test.js, test/unit/connection.test.js
Fixes https://github.com/elastic/elasticsearch-js/issues/1924 and bumps npm package version to `7.17.11-patch.1`.
=> Type declaration fix for 7.17.11

docs/changelog.asciidoc
Changelog for 7.17.11, to be merged when 7.17.11 is ready to be released.
Release is being done to push out the backported bugfix from https://github.com/elastic/elasticsearch-js/pull/1759.
=> Changelog for 7.17.11

docs/reference.asciidoc, src/api/types.ts, src/api/typesWithBodyKey.ts
Noticed that properties in the `body` were not being included in the generated API reference docs when I added argument-level docs.
=> Include body parameters in generated API reference docs

package.json
Hi,
Enabling ESM mode with TypeScript seems to cause this error to appear: `Cannot find module '@elastic/elasticsearch' or its corresponding type declarations.(2307)`
We're not ready yet to upgrade to v8.x which is why I'm patching v7.x, but it seems this error is also present in this version, and I'm not sure how to fix it yet, maybe it's as simple as declaring `"type": "commonjs"` in the package.json?
=> fix: add types to exports (v7.x)

package.json
Backport of e20ddc7e from #1930
=> [Backport 7.17] fix: add types to exports (v7.x) (#1930)

.ci/Dockerfile, .ci/make.sh
Updates the `codegen` task so that it can be run by CI. Tested via our manual GitHub action and it successfully created https://github.com/elastic/elasticsearch-js/pull/1943. :tada:
=> Update codegen task to be runnable via CI

README.md
This PR adds links to the different sections of the README file that point to the corresponding section of the getting started page. This way only the getting started documentation needs to be maintained and it will be the source of truth.
Should be backported to 8.9 and 8.8.
=> [DOCS] Restructures repo README

docs/helpers.asciidoc
Adds a section detailing how to modify documents before sending to the bulk API, using the improvement introduced in https://github.com/elastic/elasticsearch-js/pull/1732. Thanks again, @robdasilva!
=> Add docs for bulk helper improvement

src/client.ts
I fixed the user-agent to not be `elastic-transport-js` in https://github.com/elastic/elasticsearch-js/pull/1865, but the format was slightly inconsistent with other clients and the transport user-agent itself. Nothing drastic that will break client usage telemetry, just keeping things consistent.
=> Update user agent format

src/api/types.ts
Closes https://github.com/elastic/elasticsearch-js/issues/1828 by changing `flag`, `group` and `pattern` as optional properties of `AnalysisPatternTokenizer` type.
=> Fix AnalysisPatternTokenizer definition (#1828)

package.json
Upgrade transport library to 8.3.3 to take advantage of the fix in https://github.com/elastic/elastic-transport-js/pull/69.
Do not merge until https://github.com/elastic/elastic-transport-js/pull/70 is merged and published to npm. :pray:
=> Upgrade transport

scripts/utils/generateApis.js
Function 'buildPath' is defined without arguments, so I removed an unnecessary argument from the function call. 
And I removed a parameter 'param' of function 'genRequiredChecks'.
=> Remove unnecessary code

docs/changelog.asciidoc, package.json
Bumping patch to publish a fix from https://github.com/elastic/elasticsearch-js/pull/1968.
Canary has already been published.
=> Bump to 8.9.1

docs/examples/proxy/package.json, package.json
This PR replaces the names of individuals with a group name in project metadata.
=> Updated project metadata to use group name

.ci/make.sh
TIL Bash doesn't support `\d` for digits in regexes. Right now, daily automated codegen for 8.8 and 8.9 branches is running as though it is on `main` instead.
=> Fix branch name checker for automatic codegen script

src/api/types.ts, src/api/typesWithBodyKey.ts
=> Auto-generated code for 8.9

.ci/make.mjs
This change has been in main for a while but couldn't be cleanly backported to 8.8.
=> Fix codegen script for 8.8

docs/reference.asciidoc, src/api/api/indices.ts, src/api/types.ts, src/api/typesWithBodyKey.ts
=> Auto-generated code for main

src/api/types.ts, src/api/typesWithBodyKey.ts
=> Auto-generated code for 8.8

.github/workflows/backport.yml
Infosec recommends third-party actions that are maintained by individuals and not on behalf of trusted orgs like GitHub should be pinned to a specific commit.
=> Pin untrusted Github Action to a commit hash

.github/workflows/backport.yml
Backport of f72d146b0ab0f50278d0a110b29a901eab5516a5 from #1986
=> [Backport 8.10] Pin untrusted Github Action to a commit hash (#1986)

.github/workflows/backport.yml
Backport of f72d146b0ab0f50278d0a110b29a901eab5516a5 from #1986
=> [Backport 8.8] Pin untrusted Github Action to a commit hash (#1986)

.github/workflows/backport.yml
Backport of f72d146b0ab0f50278d0a110b29a901eab5516a5 from #1986
=> [Backport 8.9] Pin untrusted Github Action to a commit hash (#1986)

lib/pool/BaseConnectionPool.js, package.json, test/unit/base-connection-pool.test.js
A fix for https://github.com/elastic/elasticsearch-js/issues/1230.
=> Skip adding new nodes that aren't ready yet

README.md
Admonitions are a recent addition, and [look like this](https://github.com/pquentin/elasticsearch-js/tree/pquentin-patch-1):
=> Use GitHub admonition for browser support warning

package.json
Draft until https://github.com/elastic/elastic-transport-js/pull/72 is merged and released.
A fix for https://github.com/elastic/elasticsearch-js/issues/1230.
=> Upgrade transport: skip adding new nodes that aren't ready yet

package.json
Backport of 57e84a911432db195f7f3a93b36f6f921b5d2553 from #1995
=> [Backport 8.9] Upgrade transport: skip adding new nodes that aren't ready yet (#1995)

docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.9`:
- [[DOCS] Fix &#x60;welcome-to-elastic&#x60; link (#2007)](https://github.com/elastic/elasticsearch-js/pull/2007)
=> [8.9] [DOCS] Fix `welcome-to-elastic` link (#2007)

docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.8`:
- [[DOCS] Fix &#x60;welcome-to-elastic&#x60; link (#2007)](https://github.com/elastic/elasticsearch-js/pull/2007)
=> [8.8] [DOCS] Fix `welcome-to-elastic` link (#2007)

docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.7`:
- [[DOCS] Fix &#x60;welcome-to-elastic&#x60; link (#2007)](https://github.com/elastic/elasticsearch-js/pull/2007)
=> [8.7] [DOCS] Fix `welcome-to-elastic` link (#2007)

docs/index-custom-title-page.html
This will backport the following commits from `main` to `8.10`:
- [[DOCS] Fix &#x60;welcome-to-elastic&#x60; link (#2007)](https://github.com/elastic/elasticsearch-js/pull/2007)
=> [8.10] [DOCS] Fix `welcome-to-elastic` link (#2007)

docs/connecting.asciidoc
As noted in https://github.com/elastic/elasticsearch-js/issues/1899#issuecomment-1775751329, the docs did not indicate that `UndiciConnection` does not support proxy configurations. Updated docs and code examples to reflect how to do this properly in 8.x.
=> Improve proxy configuration docs

.github/workflows/backport.yml
This should allow us to backport PRs from forks. Copy/pasting this directly from elasticsearch-py, thanks @pquentin. :black_heart:
=> Fix backport action

docs/connecting.asciidoc
Backport of a28a6a3654b84808786c3e031e9b4e65d4e2f8f4 from #2035
=> [Backport 8.10] Improve proxy configuration docs (#2035)

docs/connecting.asciidoc
Backport of a28a6a3654b84808786c3e031e9b4e65d4e2f8f4 from #2035
=> [Backport 8.9] Improve proxy configuration docs (#2035)

package.json
Fixes https://github.com/elastic/elasticsearch-js/issues/1281.
There may be value in switching to an ES module at some point, but it's currently CommonJS so we may as well be explicit about it.
=> Set module type to commonjs

.buildkite/pipeline.yml, .github/workflows/nodejs.yml, README.md, docs/installation.asciidoc, package.json
Dropping official support for Node.js v14 and v18 as they are both [EOL](https://endoflife.date/nodejs). This mostly just means not testing code against those versions, and updating the supported version in the package.json. But future versions may take advantage of JavaScript or Node.js features that are only available in v18+.
This will be released in client v8.11 in the next week or two.
Fixes https://github.com/elastic/elasticsearch-js/issues/1855.
=> Stop supporting Node v14 and v16

.buildkite/pipeline.yml, .github/workflows/nodejs.yml, README.md, docs/installation.asciidoc, package.json
Backport of 3c5178c7aebaf435f127de29d57298519c6ac85a from #2055
=> [Backport 8.11] Stop supporting Node v14 and v16 (#2055)

.github/workflows/nodejs.yml
Multiple lines in a single filter in [paths-filter](https://github.com/dorny/paths-filter) are `OR`ed together, which means negating a list of rules filters a little too aggressively.
Switching to a single-line negative expression. The filters use [picomatch](https://github.com/micromatch/picomatch#brace-expansion) so I tested the new expression against the repo with that.
=> Path filtering improvement

.buildkite/pipeline.yml, .ci/Dockerfile, .ci/make.sh
Somehow in https://github.com/elastic/elasticsearch-js/pull/2019 I failed to see that I was causing the 8.10 branch to drift from `main` by "fixing" some problems there instead of backporting fixes from `main`. :facepalm:
=> Fix 8.10 codegen

docs/reference.asciidoc, src/api/api/ml.ts, src/api/types.ts, src/api/typesWithBodyKey.ts
=> Auto-generated code for 8.10

src/helpers.ts, test/unit/helpers/bulk.test.ts
The `bulk` helper does not support `asStream`, as it assumes the response will be parsed JSON rather than a raw stream. It currently takes a lot of debugging to understand why the helper fails in this case, so this adds an explicit check and throws an error with a clear message.
Thanks to @achyutjhunjhunwala for catching this (pun intended)!
=> Throw an explicit error when asStream is used with bulk helper

src/api/api/eql.ts, src/api/types.ts, src/api/typesWithBodyKey.ts
=> Auto-generated code for 8.11

docs/advanced-config.asciidoc, package.json, src/client.ts, src/helpers.ts
Adds support for [new redaction options](https://github.com/elastic/elastic-transport-js/pull/76) introduced in `@elastic/transport` 8.4.0.
By default, known property names that hold potentially sensitive data (like the `Authorization` HTTP header) will now have their values replaced with the string `[redacted]`.
Redaction settings can be adjusted using the `redaction` client option, which is covered in the docs.
=> Bump transport to 8.4.0

.github/workflows/npm-publish.yml
A GitHub action that, when manually triggered, will publish the specified branch to npm as the latest release, including [a provenance statement](https://docs.npmjs.com/generating-provenance-statements) to increase supply-chain security and confidence.
=> Github action for publishing to npm with provenance metadata

docs/changelog.asciidoc
This PR improves the documentation about the `body` breaking changes in 8.x.
=> Improved the body BC break description in request/response for 8.x documentation

package.json, src/helpers.ts, test/unit/helpers/bulk.test.ts
A possible fix for https://github.com/elastic/elasticsearch-js/issues/1562.
The failing state in the above issue is reached when a server's response times are slower than `flushInterval`. What happens in this situation, in this order:
1. The [`flushBytes` block](https://github.com/elastic/elasticsearch-js/blob/65580b0a2d59179ea9d63be315051588d0b25ab1/src/helpers.ts#L649-L655) awaits `semaphore()`
2. While awaiting, `onFlushTimeout` is triggered
3. [`onFlushTimeout` "steals"](https://github.com/elastic/elasticsearch-js/blob/65580b0a2d59179ea9d63be315051588d0b25ab1/src/helpers.ts#L684-L690) the bulk body rows that the `flushBytes` block is waiting to send by emptying `bulkBody` before awaiting a semaphore
4. When the `flushBytes` block's semaphore resolves, it tries to `send(bulkBody)` but …
=> Fix hang in bulk helper semaphore when server responses are slower than flushInterval

README.md, docs/installation.asciidoc
This PR adds a compatibility matrix to the Introduction section of the JS book and the repo README.
[Compatibility matrix](https://elasticsearch-js_bk_2136.docs-preview.app.elstc.co/guide/en/elasticsearch/client/javascript-api/master/installation.html#js-compatibility-matrix)
=> [DOCS] Adds compatibility matrix to docs and readme

docs/reference.asciidoc, src/api/api/text_structure.ts
=> Auto-generated code for 8.13

docs/examples/bulk.asciidoc
In the code example, the index is created with a property called 'time' but the dataset has a field called 'date.' Updating the 'date' field to match the 'time' property of the index.
=> Update bulk.asciidoc change 'date' property to 'time' to match index creation

src/client.ts, test/unit/client.test.ts
When creating connections for each node, if the node was provided as a string rather than an object, it would not inherit its client's default connection options.
Fixes https://github.com/elastic/elasticsearch-js/issues/1791.
=> Ensure new connections inherit client's set defaults

.github/workflows/serverless-patch.yml
`git format-patch` can't find a merge commit for the PR's branch because that is only available on the branch it was merged into.
=> Ensure patch can generate by checking out main branch

.github/workflows/serverless-patch.yml
- **fix: checkout multiple repos cleanly**
- **fix: ensure git apply exits cleanly**
=> Move between two repositories more cleanly during patch

.github/workflows/serverless-patch.yml
Turns out `actions/checkout` only fetches the commit provided by `ref`. `fetch-depth` set to 0 ensures that it actually fetches the full commit history.
=> More fetch depth fix to patch workflow

.github/workflows/serverless-patch.yml
Provided token was not able to push a new branch to elasticsearch-serverless-js
=> Try using default token

docs/reference.asciidoc, src/api/types.ts, src/api/typesWithBodyKey.ts
=> Auto-generated code for 8.12

.buildkite/make.mjs, .buildkite/pipeline.yml, catalog-info.yaml
Integration tests running against snapshots appear to be flaky for unknown reasons. Stop using `SNAPSHOT` builds by default for now until we can work it out.
Also reduces the number of scheduled integration test runs per day.
=> Stop defaulting to snapshots for integration tests

.buildkite/make.mjs, .buildkite/pipeline.yml, .gitignore, package.json
Bumps to 8.14.0, and makes a couple small improvements to the `make.sh bump` script.
=> Bump main to 8.14.0

docs/changelog.asciidoc, docs/helpers.asciidoc, src/helpers.ts, test/unit/helpers/bulk.test.ts
For https://github.com/elastic/elasticsearch-js/issues/2090
Includes refactor of the `tryBulk` result processing code, to make iterating over bulk response data easier to understand.
=> onSuccess function for bulk helper

docs/changelog.asciidoc, package.json
Transport version 8.5.0+ requires Node.js 18+. This ensures 8.6 users are not forced to upgrade Node.
=> Switch 8.6 clients to only get patch updates to transport

docs/changelog.asciidoc, package.json
Transport version 8.5.0+ requires Node.js 18+. This ensures 8.7 users are not forced to upgrade Node.
=> Switch 8.7 clients to only get patch updates to transport

docs/changelog.asciidoc, package.json
Transport version 8.5.0+ requires Node.js 18+. This ensures 8.8 users are not forced to upgrade Node.
=> Switch 8.8 clients to only get patch updates to transport

docs/changelog.asciidoc, package.json
Transport version 8.5.0+ requires Node.js 18+. This ensures 8.9 users are not forced to upgrade Node.
=> Switch 8.9 clients to only get patch updates to transport

docs/changelog.asciidoc, package.json
Transport version 8.5.0+ requires Node.js 18+. This ensures 8.10 users are not forced to upgrade Node.
=> Switch 8.10 clients to only get patch updates to transport

docs/changelog.asciidoc, package.json
Transport version 8.5.0+ requires Node.js 18+. While 8.11 also states it requires v18+, this fix avoids an actual breakage for pre-18 runtimes and ensures 8.11 users are not forced to upgrade Node.
=> Switch 8.11 clients to only get patch updates to transport

docs/changelog.asciidoc, package.json
Transport version 8.5.0+ requires Node.js 18+. While 8.12 also states it requires v18+, this fix avoids an actual breakage for pre-18 runtimes and ensures 8.12 users are not forced to upgrade Node.
=> Switch 8.12 clients to only get patch updates to transport

docs/changelog.asciidoc, package.json
Transport version 8.5.0+ requires Node.js 18+. While 8.13 also states it requires v18+, this fix avoids an actual breakage for pre-18 runtimes and ensures 8.13 users are not forced to upgrade Node.
=> Pin 8.13 to transport ~8.4.1

docs/examples/asStream.asciidoc
https://github.com/elastic/elasticsearch-js/issues/2241 notes that there is no body attribute on a response. This is mostly just a typo in the example, as `result` itself is a readable stream, unless `meta: true` is passed, in which case `result.body` will be a readable stream.
Also dropped the callback-style stream processing example as it's a bit outdated.
=> Update asStream code example

docs/helpers.asciidoc, src/helpers.ts, test/unit/helpers/esql.test.ts
Adds a helper function to pivot [ES|QL](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql.html) results into an array of objects.
See included documentation for details on how to use it.
=> ES|QL: Object API helper

docs/examples/reindex.asciidoc
Fix typo in example query (on [this page](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/reindex_examples.html)).
We want to match all documents where `house=stark`, not where `character=stark`.
=> Fix typo in documentation (example query)

.github/workflows/npm-publish.yml
Ensures `gh` commands can be run inside the action.
=> Add GH_TOKEN to release job

.github/workflows/nodejs.yml, lib/Transport.d.ts, lib/Transport.js, test/acceptance/events-order.test.js, test/acceptance/product-check.test.js, test/unit/transport.test.js
Backports <https://github.com/elastic/elastic-transport-js/pull/100> to 7.x client.
=> Do not retry on timeout by default

docs/changelog.asciidoc, docs/observability.asciidoc
See <https://github.com/elastic/elasticsearch-js/issues/2267> and <https://github.com/elastic/elastic-transport-js/pull/104>.
=> Documentation for OpenTelemetry support

src/api/types.ts, src/api/typesWithBodyKey.ts
=> Auto-generated code for 8.15

.github/workflows/auto-merge.yml, .github/workflows/nodejs.yml, package.json
Auto-merge PRs opened by owners of this repo. This repo is already configured to require status checks to pass (unit tests, license check, CLA, docs build) and a review approving before merging.
In effect, combining this with the auto-approve action I'm experimenting with, which will only run for PRs created by `elasticmachine`, this should auto-merge automated codegen PRs _only_ once all tests pass. It will also auto-merge PRs created by owners of this repo, but only if approved by another owner, which is a rare occurrence on this repo.
=> Add support for auto-merge

package.json
Trying to build the client started to return errors after a recent update of the `undici` package. Updating from the v17 of `@types/node` to v18 appears to address the issue.
This is the what I'm getting as output with the v17 package:
```
> tsc && rm lib/package.json && mv lib/src/* lib/ && rm -rf lib/src
node_modules/undici/types/eventsource.d.ts:13:9 - error TS2304: Cannot find name 'Event'.
13   open: Event
~~~~~
node_modules/undici/types/eventsource.d.ts:16:31 - error TS2304: Cannot find name 'EventTarget'.
16 interface EventSource extends EventTarget {
~~~~~~~~~~~
node_modules/undici/types/eventsource.d.ts:23:35 - error TS2304: Cannot find name 'Event'.
23   onopen: (this: EventSource, ev: Event) => any
~~~~~
node_modules/undici/types/filereader.d.ts:7:14 - error TS2304: Cannot find …
```
=> Upgraded @types/node package to v18

docs/basic-config.asciidoc, docs/changelog.asciidoc, src/client.ts, test/unit/client.test.ts
Fixes https://github.com/elastic/elasticsearch-js/issues/2303
=> Respect disablePrototypePoisoningProtection option

package.json, src/helpers.ts, test/unit/helpers/esql.test.ts, tsconfig.json
New helper function `client.helper.esql(...).toArrow()` returns the results of an [ES|QL query](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-getting-started.html) as an [Arrow `Table`](https://arrow.apache.org/docs/js/classes/Arrow_dom.Table.html). For #2269.
=> Basic helper for ES|QL's Apache Arrow output format

src/helpers.ts, test/unit/helpers/search.test.ts
This PR adds the `_id` field to the object returned by `helpers.search`.
A vast majority of my use cases require knowing the IDs of the documents being fetched, which is why I end up using instead the regular `search` function instead of the `helpers.search` handy helper.
At first I thought about adding an extra parameter to the function (`extraOptions`?), but after some consideration, I'm not sure that changing the existing behavior would be disruptive.  
Still, I don't mind re-implementing this feature in any other manner.
1. `_id` is an illegal field name, meaning `_source` will never include it.
2. Here is the `@es_quirk` I'm referring to in the comments (exists since version 8.14.0):
```
/**
* @es_quirk '_id' is not available when using 'stored_fields: _none_'
* on a search request. …
```
=> Add `_id` to the result of `helpers.search`

docs/changelog.asciidoc, package.json
Bumping to include the incoming change from https://github.com/elastic/elasticsearch-js/pull/2487.
=> Bump to 8.15.3

renovate.json
Updates like [this](https://github.com/elastic/elasticsearch-js/pull/2498) are not necessary.
=> Disable Dockerfile Node.js upgrades by Renovate

.github/make.sh
Prep for `main` to start referring to the 9.0.0 alpha
=> Codegen for 8.x clients should use the 8.x generator branch

src/client.ts, src/helpers.ts, test/unit/api.test.ts, test/unit/helpers/bulk.test.ts
- **Update tests and bulk helper to stop using body param**
- **Update compatible-with content-type header for 9.0**
=> Drop support for body param in helpers and tests

.github/make.sh
Codegen needs to checkout the correct branch of the generator, but was incorrectly matching on `8.x`.
=> Parse branch name during code gen including 'x'

package.json
Waiting on https://github.com/elastic/elasticsearch-js/pull/2573.
=> Bump version to 9.0.0-alpha.2

renovate.json
The Docker image version is dictated by an upstream env var so the change it keeps trying to make will have no effect anyway.
=> Another attempt to get Renovate to stop trying to upgrade a Docker image

catalog-info.yaml, package.json
Notifies Slack channel on integration test failure, updates what branches are tested. Also bumps transport to alpha.3 version.
=> Slack alerts for integration test suite

src/api/types.ts, src/api/typesWithBodyKey.ts
=> Auto-generated code for 8.16

docs/reference.asciidoc, src/api/api/esql.ts, src/api/types.ts, src/api/typesWithBodyKey.ts
=> Auto-generated code for 8.17

.github/workflows/npm-publish.yml
Determines whether to `npm publish` as "latest" or to use an alternate tag.
=> Improve npm publish version parsing

docs/docset.yml, docs/reference/api-reference.md, docs/reference/connecting.md, docs/reference/observability.md
Follow up to #2635 
When using cross-repo links, the path should be relative to the `docset.yml` not the full path within the repo ([updated docs-builder docs](https://elastic.github.io/docs-builder/syntax/links/#cross-repository-links)).
=> [docs] Clean up cross-repo links

docs/basic-config.asciidoc, src/client.ts
Also update docs to reflect its true default value and how to use it properly. See elastic/elastic-transport-js#231
=> Drop broken support for roles

docs/reference.asciidoc, src/api/api/inference.ts
=> Auto-generated code for 8.18

docs/reference/basic-config.md
Clean up a table in the Basic configurations topic that wasn't correctly converted from Asciidoc to MD.
[preview](https://docs-v3-preview.elastic.dev/elastic/elasticsearch-js/pull/2685/reference/basic-config)
part of https://github.com/elastic/docs-content/issues/690
=> [Docs] Replace mis-converted table

docs/reference/basic-config.md, docs/reference/client-helpers.md, docs/reference/configuration.md, docs/reference/connecting.md, src/client.ts, test/unit/client.test.ts
`@elastic/elasticsearch-serverless` is being deprecated, so all appropriate serverless functionality is being merged back into the main stack client.
This PR exposes a new option, `serverMode`, which can be either `"stack"` or `"serverless"`. `"stack"` keeps all defaults consistent with current behavior. `"serverless"` modifies a few defaults:
- turns off sniffing and ignores any sniffing-related options
- ignores all nodes passed in config except the first one, and ignores any node filtering and selecting options
- enables compression and `TLSv1_2_method` (same as when configured for Elastic Cloud)
- adds an `elastic-api-version` HTTP header to all requests
- uses `CloudConnectionPool` by default instead of `WeightedConnectionPool`
- turns off vendored `content-type` and `accept` headers …
=> Merge serverless functionality from @elastic/elasticsearch-serverless

.buildkite/Dockerfile, .buildkite/Dockerfile-make, src/helpers.ts
- **Update helpers to use correct multisearch types**
- **Stop copying project files to Dockerfile**
=> Update helpers to use new multisearch types

docs/reference.asciidoc
EIS won't be released in 8.18/9.0. The docs referencing EIS need to be pulled out from the generated docs. 
This PR pullso out EIS docs from ES: https://github.com/elastic/elasticsearch/pull/126381
The CI on that PR fails as one of the pages in `elasticsearch-js` links to the content I want to remove. This PR deletes the link to unblock the PR in the ES repo.
=> [DOCS]Removes link pointing to EIS reference docs

docs/reference/api-reference.md, src/api/api/inference.ts, src/api/types.ts
=> Auto-generated code for 9.0

docs/reference/timeout-best-practices.md, docs/reference/toc.yml
👀 [Preview](https://docs-v3-preview.elastic.dev/elastic/elasticsearch-js/pull/2727/reference/timeout-best-practices) 
(the release notes section at the bottom of the left nav won't be there in the full build)
This PR restores a page that was incorrectly migrated to [docs-content](https://github.com/elastic/docs-content).
I'll open a separate PR to remove this from the docs-content repo once this is merged.
=> [Docs] Restore timeout best practices

docs/reference/configuration.md
[Preview](https://docs-v3-preview.elastic.dev/elastic/elasticsearch-js/pull/2729/reference/configuration) (third link)
Missed this in https://github.com/elastic/elasticsearch-js/pull/2727 -- update the link to timeout best practices now that it's back in this repo.
=> Fix link to timeout best practices

src/helpers.ts
The ESQL helper needs to reflect the types added to the spec in <https://github.com/elastic/elasticsearch-specification/pull/4189>
=> Update ESQL helper types

docs/reference/getting-started.md
Fixes image paths to work with docs-assembler.
Notes for the reviewer:
* I was not able to get images in reference, extend, or release-notes to work using the `:::{image}` syntax because it seems to resolve differently than the Markdown `![]()` syntax. We should address this in docs-builder, but in order to get images working as soon as possible, I've used Markdown syntax and left us a `TO DO` in a code comment to add back the `screenshot` class where applicable. 
* Can you please add the appropriate labels needed for backporting?
=> [docs] Fix image paths for docs-assembler

docs/reference/basic-config.md, package.json, src/client.ts, test/unit/client.test.ts
Turns out https://github.com/elastic/elastic-transport-js/issues/231 doesn't require any actual fix in the client! Adding a test and updating docs anyway.
=> Add test to verify default node filter function

docs/reference/observability.md
The table format was making things ugly, and I added some notes to the `deserialization` event to fix https://github.com/elastic/elasticsearch-js/issues/2345.
=> Improve docs about observability event emitter

docs/reference/client-helpers.md, src/helpers.ts, test/unit/helpers/esql.test.ts
(cherry picked from commit 710b937bff82c13fd326ed8f59c1839e57baa103)
=> Use async reader for parsing Apache Arrow responses (#2788)

catalog-info.yaml
We're running them on PRs again now, so this is now more noisy than useful.
=> Stop running scheduled integration tests

index.d.ts
Fixes https://github.com/elastic/elasticsearch-js/issues/2813
=> Export helper types

docs/reference/typescript.md, index.d.ts
=> Remove dangling references to typesWithBodyKey

README.md
9.0 branch's README got out of date with `main`, causing the README on npm to be inaccurate, particularly regarding the version compatibility table.
=> Refresh 9.0 branch README

docs/reference.asciidoc, src/api/api/indices.ts, src/api/types.ts, src/api/typesWithBodyKey.ts
=> Auto-generated code for 8.19

.github/workflows/npm-publish-unstable.yml
Workflow is not being triggered as expected
=> Combine some jobs in unstable publish workflow

src/client.ts, test/unit/client.test.ts
Fixes <https://github.com/elastic/elasticsearch-js/pull/2876>
Fixes <https://github.com/elastic/elasticsearch-js/issues/2862>
=> Deep merge options on client instantiation

src/client.ts, test/unit/client.test.ts
backport 1e6cf8b58eda7ac804dfd2e5498dcb7a2a5c5a22 from <https://github.com/elastic/elasticsearch-js/pull/2890>
=> Deep merge options on client instantiation (#2890)

src/helpers.ts
ESQL types changed in the 8.19 spec. Updated the helper to reflect that.
=> Fix ESQL helper types for 8.19

docs/reference/observability.md, docs/reference/transport.md, package.json, test/unit/client.test.ts
- Adds unit tests to verify OTel disabling option
- Adds documentation for disabling OpenTelemetry
Fixes https://github.com/elastic/elastic-transport-js/issues/284
=> Docs on how to disable OpenTelemetry

.github/workflows/npm-publish-unstable.yml
Too much duplication of effort by separating the jobs.
=> Merge test and publish jobs in unstable build action

docs/reference/api-reference.md, src/api/api/inference.ts, src/api/api/info.ts, src/api/types.ts
=> Auto-generated code for 9.1

src/client.ts
Follow-up to https://github.com/elastic/elasticsearch-js/pull/2943. There's a chicken-and-egg problem with this new option so I'm going to let the TypeScript type checker fail on this PR so that it can succeed in https://github.com/elastic/elastic-transport-js/pull/285.
=> Drop @ts-expect-error

.buildkite/pipeline.yml, .github/workflows/nodejs.yml, .github/workflows/npm-publish-unstable.yml, .github/workflows/npm-publish.yml
Node.js 24 was released in May 2025 but the newest version used by the test suite is 23.
=> Run tests against Node.js 24

src/client.ts, test/unit/api.test.ts
In draft form until the code generator is updated to include the new metadata.
Part of https://github.com/elastic/elasticsearch-js/issues/2902
=> acceptedParams metadata on all API requests
