- docs/quick_start.asciidoc
I'm guessing that the exclamation mark and time are incorrect based on the statement above the code.
> Possible inconsistencies

- src/lib/errors.js
> Adding 429 HTTP status code

- docs/_examples/update.asciidoc
- docs/api_methods.asciidoc
- docs/api_methods_0_90.asciidoc
- docs/api_methods_1_0.asciidoc
- docs/api_methods_1_1.asciidoc
- docs/api_methods_1_2.asciidoc
- docs/api_methods_1_3.asciidoc
- docs/api_methods_1_4.asciidoc
- docs/api_methods_1_5.asciidoc
- docs/api_methods_1_6.asciidoc
- docs/api_methods_2_0.asciidoc
- test/unit/specs/utils.js
This commit just changes the numbers 666, which is used on some places in the tests and docs to the number 777
> Get rid of the number of the beast

- grunt/tasks.js
- src/lib/transport.js
- test/unit/specs/transport.js
> [transport/request] ensure the return value gets defined

- src/lib/nodes_to_host.js
- test/.jshintrc
- test/fixtures/short_node_list.2.0.json
- test/unit/specs/nodes_to_host_callback.js
See https://github.com/elastic/elasticsearch-py/blob/24b48852403ae3dd98b714f1914dd423c2c8ad68/elasticsearch/transport.py#L12
> [transport] use the regex used by elasticsearch-py

- docs/quick_start.asciidoc
Allows the code to be used without errors.
> Update quick start guide's complex query.

- docs/extensions.asciidoc
Adds a deleteByQuery extension to compliment the ES Delete-by-query plugin.
> Add delete-by-query extension

- src/lib/log.js
Just a style suggestion, that makes sense to me here.
[Nicer diff](https://github.com/elastic/elasticsearch-js/pull/336/files?w=1).
> Perform early return in Log ctor.

- docs/transport.asciidoc
- src/lib/log.js
- src/lib/transport.js
There were several doc changes that I didn't feel were necessary to backport, but turns out they were.
> Backport changes from jmm

- CONTRIBUTING.md
Just saw two fixes while reviewing the contributing doc. Thanks!
> Contributing spelling issues

- src/lib/log.js
- test/.eslintrc
- test/unit/specs/client.js
While checking out #378 I noticed that there wasn't a test ensuring this worked. Added one.
> added test to ensure stream log could be configured

- CONTRIBUTING.md
Should we put something in there about tagging/releasing on Github or does that happen automatically during one of these steps?
> Update contributing docs with generate/release instructions

- src/lib/apis/master.js
Regenerates master API definition using `generate` npm script.
> Regenerate from Elasticsearch master

- CONTRIBUTING.md
Signed-off-by: Tyler Smalley <tyler.smalley@elastic.co>
> Document fixing tags for preprease

- package.json
I noticed that you were missing the keywords in your package.json file, so I've added them. Let me know if there are other/different keywords that you'd use instead.
> updated package.json to include keywords

- docs/configuration.asciidoc
- docs/logging.asciidoc
- scripts/generate/templates/configuration_docs.tmpl
Just a minor spelling fix.  I have accepted the CLA for the user/email in this commit.
> sting => String

- docs/browser_builds.asciidoc
Closes https://github.com/elastic/elasticsearch-js/issues/527
> Update Browser Builds docs

- package.json
- scripts/Version.js
- src/lib/apis/5_x.js
- src/lib/apis/master.js
The `master` branch was hard-coded to be version 5.0 in the Version.js, this just increments that number.
The other approach that I was considering was adding in an optional 'branch to version' in the package.json to hopefully make it more obvious next time. Open to other alternative as well.
> Manually incrementing the hardcoded master version to 6.0

- scripts/generate/overrides.js
> Use json version of scroll api for 2.0 and greater

- src/lib/connectors/http.js
fixes https://github.com/elastic/elasticsearch-js/issues/582
fixes https://github.com/elastic/elasticsearch-js/issues/521
> fix keep alive timeout for agentkeepalive 2.x

- package.json
- src/lib/utils.js
- test/unit/specs/http_connector.js
(added a comment on each change)
> Make unit tests pass in node 8

- docs/extensions.asciidoc
> [docs/extensions] mention superagent-elasticsearch

- docs/_descriptions/explain.asciidoc
As discussed in https://github.com/elastic/elasticsearch-js/pull/713 partially solves https://github.com/elastic/elasticsearch-js/issues/469 (the rest is in https://github.com/elastic/elasticsearch/pull/34771)
> remove dead percolator link

- .ci/jobs/defaults.yml
- .ci/jobs/elastic+elasticsearch-js+master.yml
- .ci/jobs/elastic+elasticsearch-js+next.yml
- .ci/jobs/elastic+elasticsearch-js+pull-request.yml
This adds the Jenkins jobs definitions to the repo so they can be
managed and updated here.
> Add JJBB jobs to .ci

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/regression.md
- .github/ISSUE_TEMPLATE/security.md
- .github/PULL_REQUEST_TEMPLATE.md
> Added pull request and issue templates

- .ci/docker-compose.yml
- .ci/jobs/defaults.yml
- .ci/run-tests
- .codecov.yml
- package.json
> Added codecov

- .ci/test-matrix.yml
- .travis.yml
- scripts/es-docker-platinum.sh
- scripts/es-docker.sh
- scripts/kibana-docker.sh
> Use Elasticsearch 7.0.0

- docs/introduction.asciidoc
> Updated installation instructions

- lib/Connection.d.ts
- lib/Connection.js
- test/unit/connection.test.js
> Added toJSON method to Connection class

- docs/examples/typescript.asciidoc
Fixes https://github.com/elastic/elasticsearch-js/issues/876
> [DOCS] Fixes typo

- docs/configuration.asciidoc
Just adding an example of cloud configuration to the documentation as I had to look at the source code to know what to pass into the cloud object
> Added cloud configuration example

- scripts/generate.js
- scripts/utils/clone-es.js
> Support branch for code generation

- index.d.ts
- lib/Connection.d.ts
- test/types/index.ts
Fixes https://github.com/elastic/elasticsearch-js/issues/871 and https://github.com/elastic/elasticsearch-js/issues/881.
cc @mrauter @mauriciovillalobos
> Updated type definitions

- .travis.yml
- test/behavior/resurrect.test.js
> Updated travis configuration

- test/integration/test-runner.js
> Added support for arbitrary_key in integration test.

- README.md
- docs/index.asciidoc
- docs/introduction.asciidoc
Now the README is more user-friendly, it highlights better where to find the full documentation and offers a complete quick start example.
> Improve README

- docs/typescript.asciidoc
- test/types/index.ts
Hello !
I found some typo, so here is a PR to fix them.
> Fix typo in comments

- .ci/jobs/elastic+elasticsearch-js+jenkins-pipelines.yml
This is just the job configuration, the `Jenkinsfile` will follow.
> Added job configuration for Jenkins pipelines

- docs/examples/bulk.asciidoc
> Updated error handling in bulk example

- .ci/Jenkinsfile
The current definition does not work, this should fix it.
> Updated cron job definition

- docs/introduction.asciidoc
This PR fine-tunes the wording of the introduction piece in the Node.js book and improves readability.
> [DOCS] Fine-tunes the Node.js client introduction

- docs/introduction.asciidoc
This PR backports the changes of the following commit to 7.x:
[DOCS] Fine-tunes the Node.js client introduction #985
> [7.x] [DOCS] Fine-tunes the Node.js client introduction

- docs/introduction.asciidoc
- docs/usage.asciidoc
This PR backports the changes of the following commit to 7.x:
[DOCS] Fine-tunes the Node.js client usage section #988
> [7.x] [DOCS] Fine-tunes the Node.js client usage section

- docs/configuration.asciidoc
This PR fine-tunes the wording of the configuration piece in the Node.js book and improves readability.
> [DOCS] Fine-tunes the Node.js client configuration section

- docs/breaking-changes.asciidoc
This PR backports the changes of the following commit to 7.x:
[DOCS] Fine-tunes the Node.Js client breaking changes section #1012
> [7.x][DOCS] Fine-tunes the Node.Js client breaking changes section.

- docs/observability.asciidoc
This PR backports the following commit to the 7.x branch:
[DOCS] Fine-tunes the Node.Js client observability section #1055
> [7.x][DOCS] Fine-tunes the Node.Js client observability section

- docs/observability.asciidoc
This PR fine-tunes the wording of the observability section in the Node.js book and improves readability.
> [DOCS] Fine-tunes the Node.Js client observability section.

- docs/reference.asciidoc
Updated some of the anchors/page names in the SLM API ref pages so they are consistent, so these xrefs need to be updated.
Depends on: https://github.com/elastic/elasticsearch/pull/48705
> [DOCS] Updated xrefs to SLM API docs.

- test/integration/test-runner.js
> Renamed log skip function

- docs/extend.asciidoc
This PR backports the changes of the following commit to the 7.x branch:
[DOCS] Fine-tunes the Node.Js client extend the client section #1064
> [7.x][DOCS] Fine-tunes the Node.Js client extend the client section

- docs/extend.asciidoc
This PR fine-tunes the wording of the extend the client section in the Node.js book and improves readability.
> [DOCS] Fine-tunes the Node.Js client extend the client section

- test/integration/helper.js
- test/integration/test-runner.js
- Improved user and roles handling
- Avoid deleting internal indices
- Updated skip version handling
> Update integration test runner

- .ci/jobs/defaults.yml
> sync defaults with skeleton

- docs/helpers.asciidoc
- lib/Helpers.js
- test/unit/helpers/scroll.test.js
- test/unit/helpers/search.test.js
> Use filter_path for improving the search helpers performances

- test/benchmarks/actions/005_bulk.js
- test/benchmarks/actions/006_bulk-helper.js
- test/benchmarks/lib.js
- test/benchmarks/run.js
- Add outcome to event mapping
- Properly count operations
> Update benchmark scripts

- scripts/utils/generateRequestTypes.js
> Fixed types code generation

- test/unit/connection.test.js
This PR improves coverage and fixes #1125
Hi @delvedor 
It's not clear for me about all possible missing coverage.
According to [codecov](https://codecov.io/gh/elastic/elasticsearch-js/src/3efb63b34e23a11c4a93943266410defcb090616/lib/Connection.js) we need to cover [line](https://codecov.io/gh/elastic/elasticsearch-js/src/3efb63b34e23a11c4a93943266410defcb090616/lib/Connection.js#L297). Could you please check, and point if I missed something.
> improved test coverage

- lib/Helpers.js
- package.json
- test/unit/helpers/msearch.test.js
> Helpers: avoid allocating new timers

- docs/changelog.asciidoc
> Changelog for 7.8

- README.md
- docs/introduction.asciidoc
- docs/usage.asciidoc
The search API examples were incorrect, this pr fixes them.
> Fix API example usage

- lib/Transport.d.ts
- test/types/transport.test-d.ts
> Fixed transport.request querystring type

- docs/authentication.asciidoc
- docs/configuration.asciidoc
> Added sniffing blog post to documentation

- docs/configuration.asciidoc
- docs/usage.asciidoc
- index.d.ts
- index.js
- lib/Connection.d.ts
- lib/Connection.js
- lib/pool/BaseConnectionPool.js
- lib/pool/index.d.ts
- package.json
- test/acceptance/proxy.test.js
- test/acceptance/sniff.test.js
- test/types/client-options.test-d.ts
- test/unit/connection.test.js
- test/utils/buildProxy.js
- test/utils/index.js
With this pr we add out of the box support for proxies 🚀 
Related: https://github.com/elastic/elasticsearch-js/issues/101 https://github.com/elastic/elasticsearch-js/issues/286 https://github.com/elastic/elasticsearch-js/issues/402 https://github.com/elastic/elasticsearch-js/issues/483 https://github.com/elastic/elasticsearch-js/pull/613 https://github.com/elastic/elasticsearch-js/issues/843 https://github.com/elastic/elasticsearch-js/issues/1259
> Added proxy support

- .ci/jobs/defaults.yml
> Updated build failure emails recipients

- docs/changelog.asciidoc
> Changelog for 7.9

- lib/Helpers.js
- test/unit/helpers/scroll.test.js
This pull request fixes:
* #1282 - size parameter breaking scroll requests with helpers.
* #1283 - maxRetries option with value 0 results in no requests being made.
> Helper param fix

- .ci/run-elasticsearch.sh
> Updated run-elasticsearch.sh to retry on docker network failures

- api/index.js
- lib/Transport.js
- test/unit/api.test.js
- test/unit/transport.test.js
As titled.
*You don't know who is Zalgo? [Read this](https://blog.izs.me/2013/08/designing-apis-for-asynchrony).*
> Avoid the release of Zalgo

- test/integration/index.js
- Discard null values parsed froom yaml
- Crash the process in case of unhandled rejection
> Fixed integration test runner

- docs/changelog.asciidoc
> Changelog for 7.9.1

- docs/authentication.asciidoc
- docs/breaking-changes.asciidoc
- docs/configuration.asciidoc
- docs/helpers.asciidoc
- docs/index.asciidoc
- docs/installation.asciidoc
- docs/introduction.asciidoc
- docs/observability.asciidoc
- docs/testing.asciidoc
- docs/typescript.asciidoc
- docs/usage.asciidoc
This PR:
* reorganizes the introduction section,
* adds an installation section,
* adds [discrete] parameters to page sub-sections to prepare the files for proper chunking.
[Table of Contents](https://elasticsearch-js_1315.docs-preview.app.elstc.co/guide/en/elasticsearch/client/javascript-api/master/index.html)
> [DOCS] Reorganizes Introduction and Installation chapters

- test/unit/client.test.js
> Test cloud id without kibana component

- test/integration/index.js
> Skip ulong integration test test

- lib/Helpers.js
- test/unit/helpers/scroll.test.js
> Scroll search should clear the scroll at the end

- docs/configuration.asciidoc
- lib/Connection.d.ts
- lib/Connection.js
- test/types/connection.test-d.ts
- test/unit/connection.test.js
> The agent function should take the Connection contructor options as argument

- test/integration/test-runner.js
In some cases we need to update multiple stashed values inside the same string, this pr adds this behavior.
> Fix integration test

- index.js
As titled.
Related: https://github.com/elastic/elasticsearch-js/pull/1346
> Add warning log about nodejs version support

- docs/changelog.asciidoc
> Changelog for 7.10

- lib/Transport.js
- test/unit/client.test.js
As titled.
Fixes: #1347 
/cc @diegomansua
> Throw if the content length is too big

- docs/reference.asciidoc
This PR fixes a broken link that causes the docs-build process failing.
> [DOCS] Fixes link in API docs

- README.md
Update usage link in readme, current one seems to be dead (#1404)
> Update usage link (#1404)

- .gitignore
- test/bundlers/parcel-test/package.json
Parcel v1 has an issue, parcel v2 works very differently.
Hopefully, this will fix the bundler build.
> Fix test bundler

- test/integration/helper.js
- test/integration/index.js
- test/integration/test-runner.js
> Integration test: Fix yaml parser and crash on failure

- docs/changelog.asciidoc
> Updated changelog.asciidoc

- docs/helpers.asciidoc
This PR backports the following changes to the 7.x branch:
[DOCS] Reviews Client helpers section in the Node.JS book #1434
> [7.x][DOCS] Reviews Client helpers section in the Node.JS book

- lib/errors.js
- test/unit/errors.test.js
> Improve response error message

- test/integration/helper.js
> Updated integration test helpers

- lib/errors.js
- test/types/kibana.test-d.ts
- test/types/new-types.test-d.ts
- test/unit/errors.test.js
> Add top level type error to error message

- lib/errors.js
> Update body error check

- docs/changelog.asciidoc
> Changelog for 7.13

- docs/advanced-config.asciidoc
- index.js
- lib/Transport.js
- test/unit/client.test.js
> Add api compatibility header support

- .ci/run-elasticsearch.sh
- test/integration/index.js
- test/integration/test-runner.js
> Update integration test

- .github/workflows/nodejs.yml
- package.json
> Do not check for 100% coverage in coverage report

- README.md
- docs/installation.asciidoc
- lib/Transport.js
- test/acceptance/product-check.test.js
> Better message in case of unsupported build flavor

- docs/basic-config.asciidoc
> Add note about prototype poisoning protection perf

- docs/transport.asciidoc
- lib/Transport.d.ts
- lib/Transport.js
- test/unit/transport.test.js
As titled.
If this specific content type is detected, the body will be returned as a buffer.
TODO:
> Support mapbox content type

- docs/changelog.asciidoc
> Changelog for 7.14

- .ci/functions/imports.sh
- .ci/run-elasticsearch.sh
- .ci/run-repository.sh
- test/integration/index.js
Adds support for security on by default.
> Update integration test scripts

- lib/Transport.js
- test/acceptance/product-check.test.js
> Add warning.name to product check security exception

- index.js
- test/unit/client.test.js
> Fix isHttpConnection check

- test/bundlers/parcel-test/package.json
> Fix parcel build

- lib/Connection.js
- test/unit/connection.test.js
> Show socket local/remote address in case of ECONNRESET

- docs/changelog.asciidoc
> Changelog for 7.15

- docs/changelog.asciidoc
> Changelog for 7.16

- src/helpers.ts
- test/unit/helpers/bulk.test.ts
> Propagate bulk helper document generic

- CHANGELOG.md
- NOTICE.txt
> Add missing files to repo

- docs/changelog.asciidoc
> Updated changelog for 7.17

- docs/typescript.asciidoc
Fix typo: `defintions` -> `definitions`
> docs: fix typo

- docs/changelog.asciidoc
Fixes: https://github.com/elastic/elasticsearch-js/issues/1636 https://github.com/elastic/elasticsearch-js/issues/1638
> Update v8 changelog

- index.d.ts
- index.js
Closes: https://github.com/elastic/elasticsearch-js/issues/1635
> Export SniffingTransport

- docs/reference.asciidoc
This is an automatic backport to `8.1` of:
- #1654
> [8.1] [DOCS] Add discrete tags to API ref (#1654)

- README.md
This helps detecting the correct license using https://github.com/licensee/licensee
CLA signed.
> README: use correct license reference

- docs/changelog.asciidoc
> Changelog for 8.1

- README.md
- docs/advanced-config.asciidoc
- docs/basic-config.asciidoc
- docs/child.asciidoc
- docs/connecting.asciidoc
- docs/examples/asStream.asciidoc
- docs/examples/bulk.asciidoc
- docs/examples/exists.asciidoc
- docs/examples/get.asciidoc
- docs/examples/ignore.asciidoc
- docs/examples/msearch.asciidoc
- docs/examples/reindex.asciidoc
- docs/examples/scroll.asciidoc
- docs/examples/search.asciidoc
- docs/examples/sql.query.asciidoc
- docs/examples/suggest.asciidoc
- docs/examples/transport.request.asciidoc
- docs/examples/update.asciidoc
- docs/examples/update_by_query.asciidoc
- docs/helpers.asciidoc
- docs/introduction.asciidoc
- docs/observability.asciidoc
- docs/testing.asciidoc
- docs/transport.asciidoc
- docs/typescript.asciidoc
> Update connecting documentation

- src/client.ts
> More lenient parameter checks

- index.js
As titled.
Related: https://github.com/elastic/elasticsearch-js/issues/1659
> More lenient parameter checks (v7)

- .ci/Dockerfile
- .ci/make.mjs
- .ci/make.sh
- .ci/test-matrix.yml
- package.json
> Add make.sh workflows

- src/api/api/_internal.ts
- src/api/api/async_search.ts
- src/api/api/cat.ts
- src/api/api/search.ts
- src/api/api/shutdown.ts
- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Fix node shutdown apis and code generation

- docs/changelog.asciidoc
- src/helpers.ts
> Changelog for 8.2.1

- .ci/test-matrix.yml
- package.json
> Bumps 7.17 to 7.17.5

- docs/connecting.asciidoc
> Fix to proxy connection string value

- docs/reference.asciidoc
> Change 'current' to 'master' in user profile API links

- .ci/test-matrix.yml
- package.json
> Bumps 8.2 to 8.2.4

- .ci/test-matrix.yml
- package.json
> Bumps main to 8.5.0

- docs/reference.asciidoc
- src/api/api/async_search.ts
- src/api/api/ml.ts
- src/api/api/search.ts
- src/api/api/security.ts
- src/api/index.ts
- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Update APIs to 8.4-SNAPSHOT

- .ci/test-matrix.yml
- package.json
> Bumps 7.17 to 7.17.7

- .ci/test-matrix.yml
- package.json
> Bumps 8.4 to 8.4.2

- docs/changelog.asciidoc
> Add changelog for 8.4.0

- .ci/test-matrix.yml
- package.json
> Bumps 8.4 to 8.4.3

- .ci/test-matrix.yml
- package.json
> Bumps main to 8.6.0

- src/helpers.ts
> Remove @ts-expect-error

- docs/reference.asciidoc
- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Update APIs for 8.4

- docs/observability.asciidoc
- docs/reference.asciidoc
> Update all docs refs to 'current' instead of 'master'

- .ci/test-matrix.yml
- package.json
> Bumps 8.4 to 8.4.4

- .ci/test-matrix.yml
- package.json
> Bumps 7.17 to 7.17.8

- .ci/test-matrix.yml
- package.json
> Bumps main to 8.7.0

- .ci/test-matrix.yml
- package.json
> Bumps 7.17 to 7.17.9

- docs/examples/bulk.asciidoc
> [Backport main] Update bulk.asciidoc (#1752)

- docs/examples/bulk.asciidoc
> [Backport 8.6] Update bulk.asciidoc (#1752)

- docs/index.asciidoc
- docs/reference.asciidoc
This PR backports the changes of the following commits to the `7.16` branch:
> [7.16][DOCS] Includes source_branch in docs index

- docs/index.asciidoc
- docs/reference.asciidoc
This PR backports the changes of the following commits to the `7.17` branch:
> [7.17][DOCS] Includes source_branch in docs index

- docs/index.asciidoc
- docs/reference.asciidoc
This PR backports the changes of the following commits to the `8.0` branch:
> [8.0][DOCS] Includes source_branch in docs index

- docs/index.asciidoc
- docs/reference.asciidoc
This PR backports the changes of the following commits to the `8.1` branch:
> [8.1][DOCS] Includes source_branch in docs index

- docs/index.asciidoc
- docs/reference.asciidoc
This PR backports the changes of the following commits to the `8.2` branch:
> [8.2][DOCS] Includes source_branch in docs index

- docs/index.asciidoc
- docs/reference.asciidoc
This PR backports the changes of the following commits to the `8.3` branch:
> [8.3][DOCS] Includes source_branch in docs index

- .ci/test-matrix.yml
- package.json
> Bumps main to 8.7.1

- .ci/test-matrix.yml
- package.json
Bumps main to 8.8.0 instead of 8.7.0. Still getting the hang of the branching/merging/versioning dance!
> Bumps main to 8.8.0

- .ci/Dockerfile
- .ci/make.mjs
- .ci/make.sh
Get make.sh matching other clients, update targets to run on Node.js v18.
> Fixes to make.sh (#1850f

- .ci/test-matrix.yml
- package.json
> Bumps 8.7 branch to 8.7.1

- .ci/test-matrix.yml
- package.json
> Bumps 7.17 to 7.17.11

- .ci/test-matrix.yml
- package.json
> Bumps 8.7 to 8.7.2

- .ci/test-matrix.yml
- package.json
> Bumps main to 8.9.0

- catalog-info.yaml
> Fix broken cron schedule

- index.d.ts
Backport of 89f7d54 from #1784
> [Backport 8.7] Fix estypesWithBody definition (#1784)

- docs/changelog.asciidoc
Updates the changelog in the official docs to include details about 8.7 and 8.8.
> Update changelog for 8.7 and 8.8

- docs/changelog.asciidoc
Add missing header to changelog for v8.8.1
> Add missing header to changelog

- docs/changelog.asciidoc
> 7.17.12 changelog

- package.json
Accidentally committed a change while releasing the canary.
> Clean up package.json canary side effect

- .ci/Dockerfile
- .ci/make.sh
> Backport #1944 to 8.8

- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for main

- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.8

- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.9

- docs/changelog.asciidoc
> Update changelog for 7.17.13

- docs/changelog.asciidoc
Updated changelog on 8.10 branch, manually backporting here.
> Update changelog for 8.10.0

- .github/workflows/nodejs.yml
Github actions don't support YAML anchors.
> Fix unit test workflow

- docs/reference.asciidoc
- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.11

- .buildkite/pipeline.yml
- package.json
Version bump automation is currently broken for this repo. Bumping manually.
> Bump version in main to 8.10.3

- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.10

- docs/advanced-config.asciidoc
- docs/changelog.asciidoc
- package.json
- Changelog for 8.11.0
- Add redaction docs link to changelog
> 8.11.0 changelog

- docs/advanced-config.asciidoc
- docs/changelog.asciidoc
- package.json
* Changelog for 8.11.0
* Add redaction docs link to changelog
> [Backport 8.11] 8.11.0 changelog

- docs/connecting.asciidoc
Thanks to @karlbecker for the suggestion!
> Add doc for closing connections

- .buildkite/Dockerfile
- .buildkite/pipeline.yml
- .dockerignore
- catalog-info.yaml
- package.json
- test/integration/index.js
- test/integration/test-runner.js
Borrowed largely from https://github.com/elastic/elasticsearch-serverless-js/pull/38.
Also updated some metadata and pipeline configs to test the correct branches.
> Integration test improvements

- docs/doc_examples/36b86b97feedcf5632824eefc251d6ed.asciidoc
- docs/doc_examples/8575c966b004fb124c7afd6bb5827b50.asciidoc
- docs/doc_examples/bcc75fc01b45e482638c65b8fbdf09fa.asciidoc
- docs/doc_examples/d04f0c8c44e8b4fb55f2e7d9d05977e7.asciidoc
> Add missing snippets

- docs/changelog.asciidoc
* Backport changelog for 8.12.1
* Add changelog for 8.12.2
> Update changelog for 8.12.2

- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.12

- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.13

- .github/workflows/serverless-patch.yml
This is an experiment with potentially messy side effects.
> Action to apply stack client patches to serverless

- .github/workflows/serverless-patch.sh
- .github/workflows/serverless-patch.yml
- **fix: checkout multiple repos cleanly**
- **fix: ensure git apply exits cleanly**
- **Move patching script to separate file**
> Fixes to serverless patch script

- package.json
Upgrades Undici from 5.22.1 to 6.7.0.
> Upgrade transport to 8.5.0

- docs/basic-config.asciidoc
> docs: fix typo in basic-config.asciidoc

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/regression.md
And experimentally support GitHub issue forms for regression reports.
> Update issue templates to use new labels

- docs/reference.asciidoc
- src/api/api/esql.ts
- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.14

- docs/reference.asciidoc
- src/api/api/query_rules.ts
- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.15

- .github/workflows/auto-merge.yml
Trying to figure out what type of author association @github-actions has.
> Add collaborator to auto-merge

- .github/workflows/auto-merge.yml
Fixing auto-merge to use correct permissions.
> github-actions user is a contributor

- .github/workflows/auto-merge.yml
> Changes to make auto-merge action work

- .gitignore
- package.json
- test/unit/client.test.ts
Removes a security vulnerability from tap v16
> Upgrade tap to latest

- .gitignore
- package.json
- test/unit/client.test.ts
> Backport #2400 to 8.15

- test/unit/helpers/bulk.test.ts
> Skip flaky test

- docs/changelog.asciidoc
- docs/connecting.asciidoc
- docs/helpers.asciidoc
- docs/transport.asciidoc
- package.json
- src/helpers.ts
- test/unit/helpers/esql.test.ts
- tsconfig.json
Backport https://github.com/elastic/elasticsearch-js/commit/11939fd22cdecef4649877bf77eb6e27be18b028 from https://github.com/elastic/elasticsearch-js/pull/2407.
> [Backport 8.16] Add streaming support to Arrow helper

- .github/workflows/nodejs.yml
- package.json
- test/esm/package.json
- test/esm/test-import.mjs
Fixes <https://github.com/elastic/elasticsearch-js/issues/2466>
> Fix ECMAScript import

- .dockerignore
- .gitignore
- .npmignore
Fixes <https://github.com/elastic/elasticsearch-js/issues/2483>
> Ignore tap artifacts

- docs/changelog.asciidoc
- package.json
Bumping to include the incoming change from #2487.
> Bump to 8.16.2

- package.json
Co-authored-by: elastic-renovate-prod[bot] <174716857+elastic-renovate-prod[bot]@users.noreply.github.com>
(cherry picked from commit e688f363966faa5a9b42d0d8fa106d0de2bfc436)
> Update dependency @elastic/request-converter to v8.17.0 (#2555)

- src/client.ts
- test/unit/client.test.ts
> Report correct transport connection type in telemetry

- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.17

- docs/reference.asciidoc
- src/api/api/async_search.ts
- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.x

- docs/reference.asciidoc
- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.16

- .github/workflows/npm-publish.yml
Reverting an accidental revert.
> Fix npm-publish workflow

- package.json
Co-authored-by: elastic-renovate-prod[bot] <174716857+elastic-renovate-prod[bot]@users.noreply.github.com>
Co-authored-by: Josh Mock <joshua.mock@elastic.co>
(cherry picked from commit 6836a3f1c7779e4c620ce64bde81697f18819e3c)
> Update dependency @elastic/request-converter to v8.18.0 (#2642)

- docs/reference/connecting.md
Fix external links that incorrectly use `.md` instead of `.html`.
> [docs] Fix external links

- docs/reference.asciidoc
- src/api/api/inference.ts
- src/api/api/watcher.ts
- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.18

- docs/release-notes/breaking-changes.md
- docs/release-notes/index.md
* Changelog for 9.0.0
* Update title for release notes page
* Grammar tweak
* Adjustment to formatting
> Changelog for 9.0.0 (#2712)

- docs/release-notes/deprecations.md
- docs/release-notes/index.md
- docs/release-notes/known-issues.md
Backporting https://github.com/elastic/elasticsearch-js/pull/2717
> [Backport 9.0] Update release notes and related files

- src/client.ts
- test/unit/client.test.ts
> Bug #2694 (#2731)

- package.json
(cherry picked from commit 46b08caa4f76077d6ecea7d23075608604b0d63f)
> Bump version to 9.0.0 (#2749)

- docs/observability.asciidoc
Fixes https://github.com/elastic/elasticsearch-js/issues/2345
> Improve deserialization docs

- package.json
(cherry picked from commit 821e77e7ad17e141eb9fca9330c74b57b6b2b1d7)
> Support Apache Arrow 19 (#2782)

- docs/helpers.asciidoc
- src/helpers.ts
- test/unit/helpers/esql.test.ts
(cherry picked from commit 710b937bff82c13fd326ed8f59c1839e57baa103)
(cherry picked from commit 8fe778316c6932bd40fc5a55cc9f0005e27a784f)
> Use async reader for parsing Apache Arrow responses (#2788)

- docs/reference/api-reference.md
- src/api/api/ml.ts
> Auto-generated code for 9.0

- docs/reference.asciidoc
- src/api/api/inference.ts
- src/api/types.ts
- src/api/typesWithBodyKey.ts
> Auto-generated code for 8.19

- docs/release-notes/index.md
- package.json
- **Release notes for 9.0.1 (#2764)**
- **Bump to 9.0.2 (#2843)**
> Bump and update changelog for 9.0.2

- .buildkite/pipeline.yml
- .github/workflows/nodejs.yml
- .github/workflows/npm-publish-unstable.yml
- .github/workflows/npm-publish.yml
Backports https://github.com/elastic/elasticsearch-js/pull/2948
> Run tests against Node.js 24 (#2948)

- src/api/types.ts
> Auto-generated code for 9.1
